### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by OmriGalai** [JuliaLang/juliaup#1008]

**Comment by davidanthoff** [comment]
@OmriGalai do you have any more information you can provide? This is not enough for us to find out what is going on :)

**Comment by OmriGalai** [comment]
Hi, thanks for the swift reply.
I've since installed the .dmg binary directly, so if the crash report is of interest for your team - great, otherwise - I'm good.
For context, I work in R and was prompted by VS Code to install Julia for some dependency to work, so decided to give it a go.
Regards,
Omri

**Comment by davidanthoff** [comment]
If you could post the crash report it would be great, thanks!
