### ISSUE TITLE
add a progress bar

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/juliaup#102]
It would be nice if there was some kind of progress bar indicating how far along the download / the extraction is.

**Comment by davidanthoff** [comment]
At the moment I use https://crates.io/crates/ureq for the download, and I don't see any option to do something like a progress bar with it... We might have to switch http library, I think.

The big question is whether we stick with a blocking lib, or go async... I'm tempted to stick with async, seems much easier and I don't think we win anything from async for our setup... But who knows.

And also not clear what options with have with the `tar` create to report progress there...
