### ISSUE TITLE
add a "mature" channel aimed at new student users

### ISSUE THREAD

**Issue by mgkuhn** [JuliaLang/juliaup#1083]
As an instructor teaching a university course involving Julia-based practicals, I'm not sure which of the existing `juliaup` channels I should recommend to my students to use:
* `release` may at times catapult them onto a *very* fresh release (patch level 1.*x*.0, just a few days old, where the ecosystem has not yet had time to discover and iron out new incompatibilities and glitches).
*  `lts` may at times lead to a very old release, lagging years behind the state of the art.

Students in courses are usually first-time Julia users without any experience of making such judgement calls themselves. They deserve the smoothest possible experience as new Julia users, and neither `release` nor `lts` are in practice ideal for that.

I would like to see a `mature` channel that tracks `release` with a cautious/conservative delay, such that it roughly

* updates to a new “minor” release version only once per year, during the summer break (late July / early August), well before the start of the next [academic year](https://en.wikipedia.org/wiki/Academic_year) in the northern hemisphere
* avoids updating to new “minor” 1.*x* releases until issues have calmed down (e.g., there hasn't been a significant new patch release for at least ~5 weeks)
* delays updating to new patch releases for ~2–3 weeks, to leave some time for monitoring of new issues introduced by those

In case the current `lts` release is reasonably recent, `mature` might also linger on that until the end of the academic year.

(There might of course also be demand for a `mature-south` channel more in sync with the academic years of schools in the southern hemisphere.)

Managing such a `mature` channel is of course a bit more involved than the other channels, as it involves making judgement calls and liaising with various release managers and triaging teams in the Julia community, to get a sense of how “mature” a minor or a patch release has become.

**Comment by KristofferC** [comment]
This seems way too arbitrary. Just tell students what version to use in that case imo.

**Comment by davidanthoff** [comment]
I agree with @KristofferC, I think that is too specific, and I'm sure there are many, many more similar use-cases with slightly different requirements out there.

Medium term I expect that the best way to support these teaching scenarios where an instructor wants everyone to be on the same version to be solved by https://github.com/JuliaLang/juliaup/pull/1059. Essentially at that point you can distribute a project to your students, ask the students to run Julia with that project, and it will automatically ensure that they all run on exactly the right Julia version.

**Comment by ViralBShah** [comment]
I agree with the sentiment for teaching, but I think in an environment where you want least surprises, it is best to just tell students to do `juliaup add 1.10` or `juliaup add lts` or something specific for the duration of the course.

Note that you also don't want this version to change during the semester, and different universities in different parts of the world have different start and end times. As you note, this would be significantly challenging. Also different courses may have different things they need from Julia, which will lead them to use different versions.

I am closing this for now.
