### ISSUE TITLE
Juliaup launcher Crash Report

### ISSUE THREAD

**Issue by VincentPoupart** [JuliaLang/juliaup#1093]
[report-ed5ee907-dd4e-4eb6-9d3b-32c0de400547.toml.txt](https://github.com/user-attachments/files/17562786/report-ed5ee907-dd4e-4eb6-9d3b-32c0de400547.toml.txt)
`cat /tmp/report-ed5ee907-dd4e-4eb6-9d3b-32c0de400547.toml` 

'''
"name" = "Juliaup launcher"
"operating_system" = "Void Linux Rolling Release (void) [64-bit]"
"crate_version" = "1.17.9"
"explanation" = """
Panic occurred in file 'src/bin/julialauncher.rs' at line 412
"""
"cause" = 'Could not launch Julia. Verify that there is a valid Julia binary at "/home/vincent/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/bin/julia".'
"method" = "Panic"
"backtrace" = """
   0:     0x7fae763c67f4 - rust_begin_unwind
   1:     0x7fae7623d1b2 - core::panicking::panic_fmt::h1443e6472bf095a1
   2:     0x7fae762595b1 - julialauncher::run_app::h8b58b049b7670dbc
   3:     0x7fae7625bdba - julialauncher::main::hfa5d54d668acab0d
   4:     0x7fae7624b093 - std::sys::backtrace::__rust_begin_short_backtrace::h80462dd329f570f5
   5:     0x7fae7625ca13 - main
"""  
'''

**Comment by davidanthoff** [comment]
Can you check whether there is a Julia binary at that location?

**Comment by VincentPoupart** [comment]
The julia binary is effectively there, and executable by the user. I wonder if the crash is due to the fact I use the musl version of void linux instead of glibc

**Comment by davidanthoff** [comment]
Ah, yes. We don't support that scenario, see https://github.com/JuliaLang/juliaup/pull/764 at the end for a discussion.

**Comment by VincentPoupart** [comment]
Thank you very much!
