### ISSUE TITLE
Juliaup doesn't show correct version of previously installed Julia

### ISSUE THREAD

**Issue by lewisl** [JuliaLang/juliaup#1109]
I installed Julia 1.10.6 on MacOS 15.1 from the downloads page using the dmg installer.  All good.

Juliaup seems to be the latest for folks who want to manage lots of different versions of Julia installed on their machines. This seems all the rage with "new" languages. (nim also has a comparable tool).  For package developers that need to do development and testing on multiple versions, this makes sense.  This is not me.

I didn't follow the instructions to uninstall my currently installed version.  Is this the problem?  I've just been through 3 complete reinstalls because of serious problems with Julia 1.11.1.  It's takes a lot of time to get all my needed packages installed so not going to do that again.

Thought I'd get Juliaup ready on my machine so that when there is a maintenance release to 1.11 I can install it easily.  Will Juliaup take care of packages:  from readme it looks like the answer is no.

So, for my usage (YMMV) Juliaup seems to offer little benefit.  Am I interpreting all this correctly?  If so, no worries.  I can keep doing what I have always done.

So feature suggestions:
1. Scan system to find existing Julia installs and add them to Juliaup database for current machine.
2. Do something to install and upgrade packages.

It's ok if these items are not in scope for intended usage.  I'll just wait for the maintenance release of Julia and take care of upgrading the old-fashioned MANUAL way.  Hardly the end of the world but it would really be nice to improve installing an upgrade with packages.

**Comment by davidanthoff** [comment]
> Scan system to find existing Julia installs and add them to Juliaup database for current machine.

That won't work reliably, plus installing a new version of Julia with Juliaup is so painless that I don't really see the benefit.

> Do something to install and upgrade packages.

Not clear what you mean by that. Juliaup won't touch your Julia depot, so anything you installed with a previous Julia version will not be touched when Juliaup updates your Julia. Also, take a look at https://github.com/JuliaLang/juliaup/issues/44, in case that is what you meant.

I'm going to close this as I don't really see an actionable todo that needs tracking here, for general discussions discourse might be a better place.

**Comment by lewisl** [comment]
Thanks.  Juliaup doesn’t address my scenarios.  It is wicked fast at installing Julia though!

I suppose I could install an older version and then remove the later (or any) version that I don’t want. I could get used to it.

My last suggestion was the common request to install a bunch of packages from a simple list of packages.  Nothing to do with juliaup.

From: David Anthoff ***@***.***>
Reply-To: JuliaLang/juliaup ***@***.***>
Date: Thursday, November 14, 2024 at 5:58 PM
To: JuliaLang/juliaup ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [JuliaLang/juliaup] Juliaup doesn't show correct version of previously installed Julia (Issue #1109)


Scan system to find existing Julia installs and add them to Juliaup database for current machine.

That won't work reliably, plus installing a new version of Julia with Juliaup is so painless that I don't really see the benefit.

Do something to install and upgrade packages.

Not clear what you mean by that. Juliaup won't touch your Julia depot, so anything you installed with a previous Julia version will not be touched when Juliaup updates your Julia. Also, take a look at #44<https://github.com/JuliaLang/juliaup/issues/44>, in case that is what you meant.

I'm going to close this as I don't really see an actionable todo that needs tracking here, for general discussions discourse might be a better place.
