### ISSUE TITLE
"EACCES: permission denied" when running build task

### ISSUE THREAD

**Issue by ccaballeroh** [JuliaLang/juliaup#125]
When trying to build a custom image withing VS Code I get the error "EACCES: permission denied, stat ''C:\Users\Christian\AppData\Local\Microsoft\WindowsApps\julia.exe'".

I've had access permission errors before, so unistalled everything to later install Julia from the Downloads page in Julialang. That way, I was able to build the sysimage. So once again I uninstalled everything and installed Julia again using Juliaup from the Windows Store and the problem arose again.

I don't know to what folder/program to grant access so I don't get this error. Any thoughts?

**Comment by davidanthoff** [comment]
I can reproduce, will look into it, thanks for reporting!
