### ISSUE TITLE
Support for julia 1.7.0-beta4

### ISSUE THREAD

**Issue by sefffal** [JuliaLang/juliaup#137]
Hello, I currently have Julia / Juliaup installed through the windows store.
After Julia 1.7.0-beta4 was released, I attempted to install it with `juliaup` but it does not seem to be aware of the new release.

I tried the following commands:
```powershell
PS C:\Users\William> juliaup status
Installed Julia channels (default marked with *):
     1.7.0-beta3
     release
  *  beta
PS C:\Users\William> juliaup add 1.7.0-beta4
Error: '1.7.0-beta4' is not a valid Julia version or channel name.
PS C:\Users\William> juliaup add beta
Error: 'beta' is already installed.
PS C:\Users\William> julia

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-beta3.0 (2021-07-07)
 _/ |\__'_|_|_|\__'_|  |  release-1.7/e76c9dad42 (fork: 68 commits, 83 days)
|__/                   |

julia> versioninfo()
Julia Version 1.7.0-beta3.0
Commit e76c9dad42 (2021-07-07 08:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 3
```

I'm not aware if juliaup gains support for new versions automatically, or if they have to be added manually. If it's the latter, sorry for the issue spam! 

System info:
Windows 10 Pro version 21H1 Build 19043.1165

Thank you!

**Comment by msundvick** [comment]
I didn't have the beta, but `juliaup add beta` retrieved the latest version, so I'm guessing either it's been added in the last few days or it's added automatically. There seems to be the command `juliaup update` as well, so maybe `juliaup update beta` is what you want?

**Comment by davidanthoff** [comment]
Yeah, you probably just hadn't received the latest version of `juliaup` from the store?

**Comment by sefffal** [comment]
Looks like `juliaup update beta` was what I needed! Thanks.  I guess this was because I already had a `beta` version installed.
Hypothetically, what would happen if I had `julia 1.6 beta` installed and then ran `update`? Would it jump right to 1.7 beta?
