### ISSUE TITLE
Consider Cosmopolitan for cross-platform

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/juliaup#139]
Cosmopolitan supports cross-platform binaries (i.e. that libc thus your app). I've considered it for Julia itself, not sure a simple rebuild will do, but I know Rust works with it, and thus juliaup should too. Julia that you download would be platform-specific, so you just need to, at runtime, choose the right one to download:

https://www.reddit.com/r/rust/comments/klseqt/cosmopolitan_libc_buildonce_runanywhere_c/

[I haven't tried Juliaup yet (nor jill), since on Linux not Windows, and not sure it works, at least didn't locate a binary.]

**Comment by davidanthoff** [comment]
I have to admit I have no idea which problem this would solve? In general I don't want to use anything here that is not super standard and common on Rust, in my experience that always leads to some problems down the road. In particular with something like this, where I'm not even sure what problem this would solve :)
