### ISSUE TITLE
Improve help text

### ISSUE THREAD

**Issue by jebej** [JuliaLang/juliaup#142]
I was looking for the command to manually start a specific julia version (i.e. `julia +beta`) and couldn't find the syntax in the help text. I had to go back to the [discourse post](https://discourse.julialang.org/t/ann-juliaup-preview-julia-version-manager-and-windows-store-installer/61920/48).

Even though it's not `juliaup`'s job to start julia, I feel that a small "Starting Julia" section could be added to the help explaining that `julia` launches the default channel, and that a particular channel can be specified with `julia +<channel>`

I can make a PR, but I can't seem to find where to add this.

**Comment by davidanthoff** [comment]
Yes, a PR would be great!

**Comment by fingolfin** [comment]
@jebej does PR #779 do what you have in mind? If not, feel free to make a concrete suggestion what you'd do different, and I'd be happy to adjust the PR  (or of course feel free to open an alternative PR).
