### ISSUE TITLE
Possibility of factoring out the Windows Store stuff into its own repository

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/juliaup#145]
Right now, I feel all the Windows Store stuff makes the repo a bit confusing for someone who is not used to all the Windows-specific things. 

I am wondering if it is possible to have a pure "juliaup" repository (just the command line tools) and then a separate repository for all the additional stuff that is required to do the bundling etc for the Windows Store. I feel this might simplify the development and makes it a bit clearer what is specific to the Windows Store and the CLI tool.

**Comment by davidanthoff** [comment]
Maybe we just come up with a better folder structure, so that we have one folder per deployment target? There is a lot of value in the one GitHub Action workflow that handles the entire deployment story for everything…

**Comment by KristofferC** [comment]
Yeah, I guess what i mean is to have them as separate Cargo "targets" or whatever it is called. Like now, the stuff for Microsoft store like with the bundling of the Julia binary here:

https://github.com/JuliaLang/juliaup/blob/19e7e8ab0eeffc78c4e9596bfb848377cd085783/build.rs#L509-L525

is in the same build file as all the other stuff. I think it would be good if the CLI could be completely independent of the store, and then the store stuff is layered "on top" of the CLI.

**Comment by davidanthoff** [comment]
I think we've done what can be done on this one. The msix specific files are all moved into a subfolder now. But there will always be conditionally compiled code in the cli because some of the commands interact with platform specific APIs (for example, `juliaup self update` on a Windows Store installed version just has to run some Windows Store specific code).
