### ISSUE TITLE
shell completion

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/juliaup#151]
I'm not sure if the CLI generator can generate the shell completion directly in Rust (if there is one that would be better), we have shell completion auto generated via [Comonicon.jl](https://github.com/comonicon/Comonicon.jl) for IonCLI, I find this is quite convenient for terminal based people, so in case someone wants a script to start with for juliaup I wrap up a quick one here (for ZSH), I didn't open a PR because I'm not sure where would be best place to put it, but I think it would be nice if the shell completion can also be installed automatically while installing `juliaup`

In principle this shell completion can be improve to complete more specific things such as julia versions (at least in ZSH, I'm not sure about other shells), but I think this could be a start point.

```zsh
#compdef _juliaup juliaup
function _juliaup() {
    # These are set by _arguments
    local context state state_descr line
    typeset -A opt_args
    
    _arguments -C \
        '(- 1 *)'{-h,--help}'[Prints help information]' \
        '(- 1 *)'{-V,--version}'[Prints version information]' \
        "1: :((add\:'Add a specific Julia version or channel to your system'
                default\:'Set the default Julia version'
                gc\:'Garbage collect uninstalled Julia versions'
                help\:'Prints this message or the help of the given subcommand(s)'
                link\:'Link an existing Julia binary to a custom channel name'
                remove\:'Remove a Julia version from your system'
                status\:'Show all installed Julia versions'
                update\:'Update all or a specific channel to the latest Julia version'))" \
        "*:: :->args" \
}
```

**Comment by davidanthoff** [comment]
Just a note to self, there is a crate that somehow helps creating these for clap, we should try to use that when we get to this.
