### ISSUE TITLE
Stuck on 1.7-rc1

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/juliaup#154]
Juliaup has me on 1.7-rc1, but isn't providing 1.7-rc2 when I do `juliaup update`.

**Comment by visr** [comment]
The available versions are hardcoded, so unless build.rs is updated and a new juliaup version is released, new releases don't automatically become available unfortunately. Using versions.json as suggested in #131 would overcome that limitation.

**Comment by davidanthoff** [comment]
I just pushed an update that includes rc2, I was so busy with other stuff that I missed the announcement. Will take a while till it makes it through all the various stages of publishing something.
