### ISSUE TITLE
Ctrl+C ruins the terminal

### ISSUE THREAD

**Issue by MarcMush** [JuliaLang/juliaup#157]
a video is worth probably a few thousand words, so here is the issue in action

https://user-images.githubusercontent.com/35898736/142609384-27707309-fb4f-4b1f-8153-64f97880f8ea.mp4

some (most?) ctrl+C actions errors and quits Julia, and worst than that when relaunching julia in the same terminal, the input seems to be scrambled. The only solution is to start a new terminal

This only happens with juliaup (not if installed directly) and only when launched from another terminal (cmd too), it doesn't happen when I click directly on the julia app

**Comment by davidanthoff** [comment]
Yeah, I noticed the same thing on my system. I think I know what is actually happening: Ctrl+C terminates the `julialauncher.exe`, but that does (for some reason) _not_ terminate the Julia process, so it hangs around! I'll have to see how we can fix this, pretty bad bug :)
