### ISSUE TITLE
Set executable bits in CI for archives

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#159]
I noticed that the binaries didn't have the executable bit set, otherwise everything worked great though.

_Originally posted by @simeonschaub in https://github.com/JuliaLang/juliaup/issues/149#issuecomment-960076306_

**Comment by davidanthoff** [comment]
@simeonschaub I _think_ I _might_ have fixed this all now, could you maybe give it another try? I also renamed the archives that are generated for the release page, and the folder structure inside, does that make sense to you the way it is now?

**Comment by simeonschaub** [comment]
Yes, works great now!

**Comment by simeonschaub** [comment]
> I also renamed the archives that are generated for the release page, and the folder structure inside, does that make sense to you the way it is now?

The only thought I had is that it might make sense for the folder name when extracted to be version-independent. On my phone I'm currently always manually downloading and extracting the tarballs, so it would be slightly more convenient if extracting the new tarball just overwrote the old one.

**Comment by davidanthoff** [comment]
Actually, maybe we should just not have any folders in the archives? That would probably generally make it a bit easier to handle?

**Comment by simeonschaub** [comment]
Yeah, that should work too
