### ISSUE TITLE
What should the URL for the shell install script be?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#164]
The command to install this on non-Windows platforms at the moment will be
```
curl https://julialang-s3.julialang.org/juliaup/juliaup-init.sh -sSf | sh
```
The URL in there is long and ugly, and we should replace it with something nice and short. Rustup is using `curl https://sh.rustup.rs -sSf | sh`, just for comparison.

I think ideally we would use a sub-domain of `julialang.org`, rather than a new top-level domain, that generally seems more official to me. Options:
1) `sh.julialang.org` is the obvious one, that is definitely the shortest option.
2) `sh.juliaup.julialang.org` might be a bit more descriptive, but longer.

We would then also have additional URLs that correspond to pre-release versions of `juliaup`, in particular `https://sh.julialang.org/dev/` and `sh.julialang.org/releasepreview/`.

@staticfloat what do you think? Also CC @KristofferC, @heetbeet, @ViralBShah and why not @StefanKarpinski as well :)

**Comment by DilumAluthge** [comment]
> I think ideally we would use a sub-domain of `julialang.org`, rather than a new top-level domain, that generally seems more official to me.

I agree.

**Comment by DilumAluthge** [comment]
What is the long-term plan for `juliaup`? Is the idea that once `juliaup` supports Windows, macOS, and Linux, that we can advertise `juliaup` as the officially recommended installation method, at least for the majority of Julia users, and definitely for Julia beginners?

If so, I would go for `sh.julialang.org`.

**Comment by davidanthoff** [comment]
> What is the long-term plan for `juliaup`?

Good question ;)

> Is the idea that once `juliaup` supports Windows, macOS, and Linux, that we can advertise `juliaup` as the officially recommended installation method, at least for the majority of Julia users, and definitely for Julia beginners?

I think at some level it would be great if it worked out that way, so I'd say that is the aspiration. On the other hand, that is still a long road and I think we need a lot more real-world feedback and usage before that can really be decided. This whole project was also largely developed independently (with a few exceptions) from the core Julia dev group, so minimally they need to let us know what they think about this. But, with all these caveats, from my end it would be great if that is where we end up.

I should say that I would also favor `sh.julialang.org`.

**Comment by davidanthoff** [comment]
I guess another option would be `juliaup.julialang.org`. but I don't really like it because people might browse to that and expect a webpage, but then they would just get a shell script... Plus, I think the long term goal would be that users install Julia with this shell script without necessarily knowing what `juliaup` is, I think ideally they would just think "this is the way to install Julia".

**Comment by ViralBShah** [comment]
I prefer Juliaup.julialang.org. we can have a basic page up there for people who accidentally find it. 

What does sh refer to?

**Comment by ViralBShah** [comment]
We have juliaup.org now.

**Comment by StefanKarpinski** [comment]
`.up` isn't a TLD and probably never will be — there's no country with `.up` as their TLD and two-letter TLDs are reserved for countries. So unless a new country is formed with `.up` as their TLD, this won't ever become available. Using `juliaup.org` for the landing page and `sh.juliaup.org` or `https://juliaup.org/script` or something like that seems good.

**Comment by ViralBShah** [comment]
@staticfloat meant .up tongue in cheek, I believe.

**Comment by StefanKarpinski** [comment]
I mean, if we're going to `shell out $$$` for a two-letter TLD, we should go for starting the nation of Juliastan and have its TLD be `.jl` and only allow it to be used for Julia packages 😁

**Comment by davidanthoff** [comment]
So, the way I've been thinking about this is that I kind of hope that about 80% of users eventually will never have to know what `juliaup` is, even if they _are_ using it. I kind of imagine something where a new user goes to julialang.org, and then there is a "Getting started" link that says to run `curl https://sh.julialang.org -sSf | sh`. They do that, at no point is `juliaup` mentioned, but then they can just type `julia` and everything works.

Then, when a new Julia release is tagged, the next time they run `julia` they are prompted with something like `Hey, a new Julia version was released, do you a) want to update right away, b) be reminded later or c) ignore this update?` And while that experience is under the hood powered by `juliaup`, the user again wouldn't have to know that `juliaup` even existed for this particular interaction.

Same thing with the following scenario: user starts `julia` in a folder with a `Manifest.toml` that has a specific Julia version recorded. Again they get a prompt that says something like `Hey, the project you are loading has Julia version X recorded, but you are on version Y. Do you a) want to download version X and use that, or b) use existing version Y?` And again this would be powered by `juliaup`, but the user would essentially be completely unaware of that.

So in my mind that would probably cover a very, very large fraction of the user base. And then more advanced users could actually start to call `juliaup` directly if they really want to multiplex versions etc.

I am a bit worried to throw things like "you'll use juliaup to manage your julia version" at novel users, that very quickly gets quite complicated and confusing, and my best guess is that most of them actually will have no need to ever interact with `juliaup` directly.

So, in any case, the more I think about it, the better I think it would be if we used `sh.julialang.org` for the shell install scripts. We could still use `juliaup.org` for some landing HTML site, although it might even be better to just mention `juliaup` in the normal julialang docs eventually?

**Comment by ViralBShah** [comment]
I think either URL is fine. Also once the tool gets some momentum, we should certainly mention it in the manual.

Do things like ssl certificates drive us to one option vs another?

**Comment by davidanthoff** [comment]
Should we for now just create `sh.julialang.org` to move this forward? In general, that URL could be changed later relatively easily, so whatever we do now is not set in stone forever.

@staticfloat I assume you would set this up? Would this be another S3 bucket that holds that data? And the ssl certificate thing is also something that we would need to sort out...

**Comment by ViralBShah** [comment]
I think sh.juluaup.org is easier as we can do whatever we want there and experiment and move to julialang.org later.

However whatever @staticfloat feels is best

**Comment by StefanKarpinski** [comment]
I love this vision of how people interact with this! Can I suggest that we make the domain something like `install.julialang.org` or maybe `julialang.org/install.sh`? The latter seems easiest to me. I tried adding an `install.sh` file to the `julialang.org` repo and that gets served verbatim, so it's simple.

**Comment by davidanthoff** [comment]
Is `julialang.org` hosted as github pages? If there is a way that I can push new versions of `julialang.org/install.sh` via a GitHub Action, then this should be super simple to implement.

**Comment by StefanKarpinski** [comment]
It's not github pages but it is automatically deployed when changes are made. I'm not certain if it's only triggered by pull requests or if it's also triggered by pushing to master, but I can give it a try...

**Comment by StefanKarpinski** [comment]
Ok, we intentionally disallow pushing to main, so it may be necessary to make a PR to update it, although we can probably figure out how to automate the whole thing. I guess the advantage of a separate subdomain is that the entire subdomain could be automatically deployed from the juliaup repo.

**Comment by simeonschaub** [comment]
We could also just make `julialang.org/install.sh` a redirect

**Comment by StefanKarpinski** [comment]
That's a bit hard to do from Franklin (at least I don't know how to do it).

**Comment by davidanthoff** [comment]
So maybe the subdomain is easier, we could just have some S3 bucket that is directly surfaced as `install.julialang.org`, then we would just reuse the already existing code in the Github workflow to publish things there.

**Comment by ViralBShah** [comment]
I believe julialang.org is hosted on github pages - on the gh-pages branch (but we have the whole netlify based CI system to make sure things don't break). It was mainly to avoid dealing with the julialang.org setup that I suggested using juliaup.org, where you can pretty much set it up however you want it.

**Comment by davidanthoff** [comment]
I think really what we should do is a) have a S3 bucket that we can push the scripts to from the GitHub workflow, and b) then just map _some_ DNS to that bucket, and make sure we have `https` for that, i.e. a certificate.

**Comment by ViralBShah** [comment]
@staticfloat Can you suggest the most robust way to do this for now? I feel `juliaup.org` would be best, but you may have a better view. Can we use letsencrypt.org to get a wildcard certificate for `juliaup.org`?

**Comment by staticfloat** [comment]
I think a subdomain is the easiest way to avoid having to deal with Franklin stuff.  Let's start with `install.julialang.org` for now.

I've setup an S3 bucket called `juliaup-install`; I can give upload permissions to David as needed.  Right now, there's only one file in there, `install.sh`.  I've got a Fastly configuration pointing from `install.julialang.org` to that S3 bucket, so you can get e.g. https://install.julialang.org/install.sh.  I feel we may eventually want a landing page if someone goes there in a browser, but we can deal with that when we get there.

**Comment by StefanKarpinski** [comment]
We can always change what we serve based on the user-agent, although I hate it when sites do that. Maybe better to just serve the script from `/` but put comments in the script explaining what people are seeing, rather than a landing page?

**Comment by davidanthoff** [comment]
One thing: it actually would be nice if we pick the "final" URL now. I'm sure folks will make tutorials/videos whatever about this, and just having something that never ever changes again would be nice for that.

So I think for now, we're aiming for
```
curl https://install.julialang.org -sSf | sh
```
Which I think is nice! I'll connect with @staticfloat to set up the publishing of the scripts hopefully soon, my mega project that has kept me from most of my Julia stuff in the last months is done :)

**Comment by davidanthoff** [comment]
I have another idea :) What about `i.julialang.org`? The command then would be
```
curl https://i.julialang.org -sSf | sh
```
Some nice things about this:
- It is _really_ short, which will be nice for the serial-Julia-installers among us who end up memorizing this command and then type it from memory.
- It is a bit more obscure, so maybe folks are less likely to try that URL in their browser, a good thing. I'm a bit worried that folks will start to browse to `https://install.julialang.org` a lot, just because it kind of invites that.
- For the casual user, they will just copy paste this command from some "Getting Started" page, so for those users it doesn't really matter what the URL is in any case.

**Comment by StefanKarpinski** [comment]
I think we should stick with https://install.julialang.org and the script can have a comment that explains that it's not a web page. I don't think the shorter URL is better—most people don't type this often or even ever, they cut and paste it. For the rare people who have need to install juliaup often, an alias would seem to be even shorter, no?
