### ISSUE TITLE
Should arch linux dist have self update?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#169]
@simeonschaub really a question for you: should the build that we ship on arch linux have the self update feature enabled? Probably not, because the arch package manager is presumably handling updates of `juliaup` itself, right?

**Comment by davidanthoff** [comment]
Ah, wait, that is actually already happening, because you are not deploying the binaries we compile in the Github workflow, but instead compile from source for the arch distribution, right? And by default the self update feature won't be included at the moment if one compiles from source.

**Comment by simeonschaub** [comment]
Yes, I think the current setup works quite well, so I don't see anything actionable here, at least for now. We can always revisit this later on.
