### ISSUE TITLE
feature: ability to list channels

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/juliaup#171]
I may have missed if from poking around the CLI, but I couldn't figure out how to get a list of the available channels, which would, of course, be a useful feature.

**Comment by davidanthoff** [comment]
I'm wondering whether we should just add that to the documentation of `juliaup add`? The list of channels is very long, essentially all combos of x.y.z, x.y, x, plus `lts`, `release`, `beta` and `rc`. So we probably don't want to list them all, but give some verbal explanation of the pattern. I guess if `juliaup add --help` just printed the same explanation I just gave here, that might do it?

**Comment by StefanKarpinski** [comment]
Sure, that documentation would work, although I would also be ok with a long list being made available, maybe with some way to filter it down, maybe with shell globs?

**Comment by davidanthoff** [comment]
`winget` has a `search` command that works like this:
```
Searches for packages from configured sources.

usage: winget search [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query                  The query used to search for a package

The following options are available:
  --id                        Filter results by id
  --name                      Filter results by name
  --moniker                   Filter results by moniker
  --tag                       Filter results by tag
  --command                   Filter results by command
  -s,--source                 Find package using the specified source
  -n,--count                  Show no more than specified number of results (between 1 and 1000)
  -e,--exact                  Find package using exact match
  --header                    Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements  Accept all source agreements during source operations
```
We could do a similar thing, i.e. `juliaup search` just shows a list of all available channels, and then later on we can add the ability to filter, like you suggested with globs or something else?

Is `juliaup search` a good name, or is there better precedence in a different tool?

**Comment by StefanKarpinski** [comment]
Calling it `juliaup list` and just dumping all names would be fine with me since you can always pipe it to `grep` (or whatever your preferred filtering tool is).

**Comment by MatthijsBlom** [comment]
Some precendent:

- `$ rustup toolchain`: only lists installed toolchains, but has exemplary documentation. 
- `leanprover/elan` copies `rustup`.
- `$ ghcup list` lists all available compilers and tools &ndash; 41 items at the moment.

> Is `juliaup search` a good name, or is there better precedence in a different tool?

I would expect `search` to accept arbitrary terms that it would search for. Is this the intention?

If I'm understanding the intention correctly, I think I'd go with something more like `list`, and filter using flags. One could also go with a `rustup toolchain`-style `channel` (for general management, though there is already `add`) or `channels` (for listing available channels). 

**PS** In the future there may arise a need for something like `rustup component`.

**Comment by ViralBShah** [comment]
Also wanted this feature as soon as I installed `juliaup`.

**Comment by johnnychen94** [comment]
How about letting `juliaup list` show the installed channels and `juliaup list --all` show all available channels? For instance,

```julia
$ juliaup list
lts
release
...

$ juliaup list --all
lts ✅
release
...
```

Having two subcommands for very similar purposes seems unnecessary to me.

**Comment by davidanthoff** [comment]
Hm, the problem is that we already have `juliaup status`, so then `juliaup list` would do the same thing, right? That is probably not ideal...

**Comment by StefanKarpinski** [comment]
The API isn't set in stone yet. You could make `status` an alias for `list --all`. I'd also be ok with `status` and `list`.

**Comment by davidanthoff** [comment]
I'm sticking with `status` and `list` for now. I like the symmetry with the package manager for `status` in particular, and in general I'm a fan of only providing one way to do things :) 

We might need additional flags for `list` to filter that list a bit, right now it is a _very_ long list... Might make sense to filter out prerelease versions by default, or other platforms, or something... Not sure, though.
