### ISSUE TITLE
Add clearer information about channel selector

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaLang/juliaup#185]
I just looked around the README for this project, as well as the discourse announcement of `juliaup`, AND tried multiple commands for some time before seeing that you choose a channel to launch from with the `+` symbol.
This should be clearer in the README, and especially in the `help` command for `juliaup`.

Something like
"To launch the Julia version in channel `lts`, run `julia +lts` in your terminal".

**Comment by davidanthoff** [comment]
Yes, agreed! A PR would be very welcome :)

**Comment by KronosTheLate** [comment]
Closed by https://github.com/JuliaLang/juliaup/pull/187
