### ISSUE TITLE
What should be the default platform served on Mac M1?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#186]
At the moment, the `release` channel on M1 serves x64 binaries. Should we change that to go with the new aarch64 builds starting with version 1.7? Or are they too new and experimental and only tier 3 support? CC @StefanKarpinski

**Comment by DilumAluthge** [comment]
I would say that for now, the ARM binaries are still experimental enough (and tier 3) that we should continue using the x86_64 binaries by default. And then maybe we can reevaluate that decision after 1.8.0 or 1.9.0.

If a user does want to use juliaup to install the 1.7.0 ARM release binaries, what is the command for doing so?

**Comment by deoradh** [comment]
I would think `aarch64`, but I'm not certain it's supported yet?

On my M1 Pro:

```
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.


~
❯ juliaup --version
Juliaup 1.5.2

~
❯ juliaup status
 Default  Channel  Version      Update
---------------------------------------
       *  release  1.7.1+0~x64

~
❯ juliaup add 1.7~aarch64
Error: '1.7~aarch64' is not a valid Julia version or channel name.

~
❯ juliaup add 1.7~x86
Error: '1.7~x86' is not a valid Julia version or channel name.

~
❯ juliaup add 1.7~x64

~
❯ juliaup status
 Default  Channel  Version      Update
---------------------------------------
          1.7~x64  1.7.1+0~x64
       *  release  1.7.1+0~x64

~
❯
```

**Comment by davidanthoff** [comment]
I think what we should definitely add is the option to do `juliaup add release~aarch64` to get the new versions. My understanding is that we should wait though to make that the default for say the `release` channel until things are more stable, and keep shipping the `x64` versions in the non-arch specific channels?

**Comment by deoradh** [comment]
I think that's a reasonable approach until there's confidence in the aarch64 deployments.  At the least, we can then use juliaup while testing them out.

**Comment by davidanthoff** [comment]
Yes, there definitely needs to be some way to find out what channels exist :) At the moment I'm still working on getting the Mac and Linux support to a basic "it works" state, so that is my priority right now, but PRs with better help text for example would be great!
