### ISSUE TITLE
Windows 11: After installing Julia from the Microsoft Store, VSCode cannot find it

### ISSUE THREAD

**Issue by IljaK91** [JuliaLang/juliaup#188]
Hello everyone,

I installed the newest version of Julia (1.7) on my Windows 11 computer using the most up-to-date version of VSCode and the Julia VSCode extension. However, VSCode cannot find the julia installation. I verified that Julia is on the path and executing it from the command line works without problems. Also, there are no issues on Windows 10 with the same setup.

Does anybody know how I can fix this?

Best,
Ilja

**Comment by davidanthoff** [comment]
Do you maybe have something configured in VS Code for the `Julia: Executable Path` setting? That should be empty.

**Comment by IljaK91** [comment]
It is indeed empty, but it stil does not work.

**Comment by davidanthoff** [comment]
And just to be sure: you installed Julia from the Windows Store, you don't have any other Julia versions installed, and things like `juliaup -V` work, and when you type for example `julia +release` on the command line it works?

**Comment by IljaK91** [comment]
Yes, just checked all of that.

**Comment by IljaK91** [comment]
I am also getting this error message, if I try to execute a line nonetheless:
```
Command failed: julia.exe --startup-file=no --history-file=no -e using Pkg; println(dirname(Pkg.Types.Context().env.project_file)) ERROR: ArgumentError: Package Pkg not found in current path: - Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package. Stacktrace: [1] require(into::Module, mod::Symbol) @ Base .\loading.jl:967
```

**Comment by davidanthoff** [comment]
Is the problem that VS Code can't start a Julia REPL, or is the problem with the language server? Also, I merged some stuff in the VS Code extension a while ago that might also have helped (if the problem was on the language server side of things).

**Comment by IljaK91** [comment]
I tried it again today and everything worked just fine. Seems to have been some fluke or fixed in other updates! :)
