### ISSUE TITLE
Should `julialauncher` just be called `julia`?

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/juliaup#189]
IIUC, the vision here is that users will primarily interact with Julia through Juliaup's launcher, so I think it would make sense to call that the primary `julia` command. I am not sure whether there are any special considerations for Windows here.

**Comment by davidanthoff** [comment]
Yeah, I thought about this. One benefit of the current setup though is simply that in Task Manager I can tell which process is which very easily, which can be quite helpful. And at least on Windows the store installer automatically creates a symlink from `julia` to `julialauncher`, so from a user point of view this is handled pretty transparently.

Not sure whether that task manager reasoning applies to other platforms as well?

**Comment by simeonschaub** [comment]
That's a good point. On Linux `htop` usually shows the the full directory of the running command, so it would still be distinguishanle, but I could see that possibly being confusing. Perhaps we should just create a symlinks on Linux and MacOS in the default installer as well?

**Comment by simeonschaub** [comment]
Ok, I have now changed the AUR recipe so that it creates `julia` as a symlink to `julialauncher`.

**Comment by davidanthoff** [comment]
Should we close this issue, and say we generally leave the name and try to create symlinks?

**Comment by simeonschaub** [comment]
Yes, I think we can
