### ISSUE TITLE
juliaup denies updating release channel to 1.7.1

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/juliaup#191]
```
C:\Users\Aaron>juliaup st
 Default  Channel  Version      Update
---------------------------------------
       *  release  1.7.0+0~x64

C:\Users\Aaron>juliaup update

C:\Users\Aaron>juliaup --version
Juliaup 1.5.0

C:\Users\Aaron>juliaup st
 Default  Channel  Version      Update
---------------------------------------
       *  release  1.7.0+0~x64
```

**Comment by davidanthoff** [comment]
You don't have the latest `juliaup` version. You can either wait until the Windows Store auto updates it in the background, or you can go into the Windows Store and check for updates, or you can also try to run `juliaup self update`, which should in theory trigger a store update :) I'm going to close for now, but if none of these options work, please reopen this issue.
