### ISSUE TITLE
Updates to .bashrc even when other shell is used

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/juliaup#219]
Just tried it for Linux - very cool!

After installing, it updates my PATH in .bashrc - but I use `nushell`. Now, it's completely fair not to support all shells out there, but
* MacOS uses `zsh` by default. I haven't tried Juliaup on MacOS, but please check that it updates `.zshrc` instead of `.bashrc`
* The message after installation is "Run `. ~/.bashrc` to reload $PATH variable." - it should probably mention that it assumes you are running from Bash

**Comment by davidanthoff** [comment]
Yep, completely forgot about that :) Next on my list. One question: for zhs, can we just add the same shell script fragment to `.zshrc` that we are adding to `.bashrc`, or is that not "valid" zhs?

Also, I think it would be fine to support as many shells as we can, so as long as we can figure out how to handle `nushell`, lets support it as well.

**Comment by StefanKarpinski** [comment]
Valid bash code usually works in zsh as well. I'm happy to give it a try as a zsh user.

**Comment by davidanthoff** [comment]
Ok, it now also supports zsh, and the printed messages are also no longer bash specific.
