### ISSUE TITLE
PATH propagation for zhs

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#223]
hmm... So I'm launching pwsh via `/bin/zsh --login -t -c pwsh` (also how I define my Julia, Wolfram, etc profiles).  I used to get the path via the path.d mechanism, but I'm not getting any path change from this?

Adding `source ~/.profile` to .zprofile brought things in.

_Originally posted by @deoradh in https://github.com/JuliaLang/juliaup/issues/174#issuecomment-1013639350_

**Comment by davidanthoff** [comment]
Was your `.zshrc` file modified? That is the one change I'm making for zsh at the moment. I would have thought that the command `/bin/zsh --login -t -c pwsh` would run that? But maybe not? My understanding was that `.zshrc` always run and that that would be the one place where we need to make modifications on MacOS? @StefanKarpinski any ideas?

**Comment by deoradh** [comment]
it was:

```
eval "$(starship init zsh)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

path=('/Users/kfarmer/.juliaup/bin' $path)
export PATH

# <<< juliaup initialize <<<
```

**Comment by davidanthoff** [comment]
So that suggests that for some reason `.zshrc` is not sourced when you run your command, right? I guess the question now is why is that :)

**Comment by davidanthoff** [comment]
Ok, so I don't really know what to do about this :) I think what is happening is that
- we correctly modify `.zshrc`
- for some reason running `/bin/zsh --login -t -c pwsh` does _not_ run `.zshrc`.

It is not clear to me whether it should do step 2 or not, or what the correct way out of this is. Maybe @StefanKarpinski has an idea?

**Comment by davidanthoff** [comment]
Bump, does anyone have any more insights on this? It seems to me that this is not a broad problem, otherwise we would probably have heard more bug reports about this? So, I'm tempted to close this issue, unless someone chimes in with more info what we need to do here.

**Comment by davidanthoff** [comment]
I'm going to close this for now. We must have very many zhs users, namely everyone on Mac, and given that none of them had this problem, I'm just hoping that this was a machine specific issue :)
