### ISSUE TITLE
"Use 0 to disable" -> "Not a valid input"

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/juliaup#225]
When trying to disable background task update checks, I found that trying to use `0` to disable the check didn't work, I had to use just a blank input.

![image](https://user-images.githubusercontent.com/130920/150018903-004c7314-e772-4fb7-858b-733af7f17f63.png)

**Comment by davidanthoff** [comment]
I went back to the old UI library now, I think this should be fixed with that.
