### ISSUE TITLE
PATH modification customization not working

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/juliaup#226]
I tried to disable PATH modification, but it appears that it didn't listen to me.  😂 

![image](https://user-images.githubusercontent.com/130920/150019182-562ab2fc-cd1e-453f-bb46-57d3865f9b6b.png)

**Comment by davidanthoff** [comment]
It is lying to you ;) But we should update the message there and only show the part about the PATH modifications when they are actually going to happen.

**Comment by davidanthoff** [comment]
Ok, I think this should be fixed in the latest build.
