### ISSUE TITLE
x86 for 64 bit or 32 bit?

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/juliaup#235]
Thanks, this looks fantastic! Just a small comment:

In the Julia downloads page, `x86` refers to the whole family, including 32-bit and 64-bit.

<img width="1174" alt="Schermafbeelding 2022-01-21 om 12 24 37" src="https://user-images.githubusercontent.com/6933510/150519094-57499a0b-9168-4ada-b0ce-f61e7f067844.png">

On an ARM-based computer (like the new macs), I would expect `juliaup add 1.7.1` to install the ARM 64-bit build, and `juliaup add 1.6.1~x86` would install the x86 64-bit build, not the 32-bit build.

On the README: it states: 
> `juliaup add 1.6.1~x86` installs the 32 bit version of Julia 1.6.1 on your system.

Is this intended? Maybe we can use `~x86-64` and `~x86-32` to specify?

**Comment by davidanthoff** [comment]
> I would expect `juliaup add 1.7.1` to install the ARM 64-bit build

Yes, that will happen once the ARM builds are stable (i.e. tier 1), but for now I've configured it such that this delivers the x64 build on Mac.

> Is this intended?

Yes, sort of ;) This project started as a Windows only solution, and there x86 typically refers to the 32 bit version and x64 to the 64 bit, and both are nice and short. Not sure how to best handle that, I think on Windows those are probably the best suffixes, but maybe not on other platforms? I guess we could use different platform specifiers based on OS? There is also a complication that the Windows version of this is released and shipping, so if we wanted to change anything we would need to handle the update path, which might be non-trivial.

**Comment by davidanthoff** [comment]
I do think that if we want to make any change here for Linux/Mac, then we should do it now, that would be much, much easier than doing this later once we have things officially released on those platforms.

So, one proposal could be platform specific endings. That would mean:
- On Windows we have the suffices `~x86` (32 bit), `~x64` (64 bit) and down the road maybe `ARM64` and/or `ARM` (I only found https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm on the naming of the various Windows ARM platforms, not exactly clear what the canonical names are...)
- On Mac we would have `~x86` (which then gets you the 64 bit versions) and I guess `~aarch64`?
- On Linux `~x86-32`, `~x86-64` and `~aarch64`, maybe?

That all seems terribly inconsistent, though... But maybe that is the price we have to pay if we want to use the most common terms per OS?

I guess the alternative would be to use just one set of platform specifiers everywhere, so maybe that would then be what @fonsp suggested, i.e. `~x86-32`, `~x86-64` and `~aarch64`. But I really don't like the idea of changing things for the existing Windows users, and none of these three names are what is commonly used on Windows to refer to any of these platforms, AFAIK...

Wondering whether @staticfloat, @StefanKarpinski or @KristofferC have thoughts on this?

**Comment by staticfloat** [comment]
I think whatever we do should be consistent.

Our typical names for architectures tend to follow the first element in a GCC triplet, and then we have various "short names" for them:

* `x86_64`, also known as `x64`
* `i686`, also known as `x86`
* `armv7l`, also known as `arm`
* `aarch64`, also known as `arm64`
* `powerpc64le`, also known as `ppc64le`

I think using the short names here are acceptable, as is just using the full arch name.  I definitely don't think that `x86` should mean something different depending on your host architecture; keep it consistent so the noun is the same everywhere.

**Comment by davidanthoff** [comment]
So that would mean we use `x64`, `x86` and `arm64`? That works for me, is all nice and short and has the benefit that we don't have a breaking change for the "shipping" Windows version. We would have to change `aarch64` to `arm64` on Mac and Linux, but given that we haven't released that version officially, that would be a very easy change.

**Comment by staticfloat** [comment]
The benefit of `arm64` vs. `aarch64` is marginal to me; I'm happy either way.  Mostly I think `ppc64le` is much preferable as compared to `powerpc64le`, and `x64` instead of `x86_64` is nice because it dodges the need to press shift so much.  :P

**Comment by davidanthoff** [comment]
I just looked through the source code, and changing `aarch64` to `arm64` would touch a lot of places. And given that I'm with @staticfloat that I don't really care about that particular difference, let's just leave everything the way it is :) So `x64`, `x86` and `aarch64`.
