### ISSUE TITLE
Document How To Uninstall

### ISSUE THREAD

**Issue by Firionus** [JuliaLang/juliaup#240]
**Synopsis** 
Document how to uninstall in README and juliainstaller

**Full Text**
Since `juliaup self uninstall` seems to work in the current release, it would be great if this functionality would be documented in the README. 
I tried around a few minutes with `juliaup remove self` or `juliaup self remove` until I found the proper command in an issue. 

Would also be good to mention it in the installer when a pre-existing version of juliaup is found. Currently it only shows:
```sh
$ curl -fsSL https://install.julialang.org | sh

info: downloading installer
Welcome to Julia!

It seems that Juliaup is already installed on this system. 
Please remove the previous installation of Juliaup before you try to install a new version.
```

Cheers, and special thanks to @davidanthoff for his amazing work on this project :rocket:

**Comment by LilithHafner** [comment]
Does this block release as the official Julia version manager?

**Comment by StefanKarpinski** [comment]
Yeah, we should probably have the docs for this before making it official, otherwise people will ask.
