### ISSUE TITLE
feature: include installation paths in API

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/juliaup#242]
The installation paths are currently not in the API. I saw somewhere that @davidanthoff had done this intentionally, but had not made a firm decision. I find complicated, un-documented installation trees unpleasantly enterpris-y, but I am in a small minority. There are big advantages to hiding the paths, especially in the early stages of development. I'm asking what the status is and I give a use case below. But, I understand that the pros of hiding this detail may outweigh cons.

I have a specific use case. I am interested in trying to package python projects that depend on Julia in such a way that the user does not have to know that Julia is involved; it's just `pip install ...` like any other Python package. In many environments, this is essential for adopting Julia (until Julia rules the world and calls the shots). For example Python packages with compiled C or rust shared libs can be distributed this way. This was a necessary condition, for example for adopting a [rust](https://github.com/Qiskit/retworkx) library in the IBM Qiskit ecosystem.  This library is a successful open-source project that has industry support. Doing this right now for Julia is perhaps a bit quixotic, but I suspect it is in fact not too quixotic. I am developing a (rather simple) package [julia_project](https://github.com/jlapeyre/julia_project) that manages a Julia dependency in a Python project. It depends on another package [find_julia](https://github.com/jlapeyre/find_julia) whose sole responsibility is search for Julia installations (with some support for coarse version requirements) on a system, and return a path, or offer to install Julia if none is found.

I'd like to include juliaup installation paths in `find_julia`. If the user chose to put the julia executable parent dir in their PATH, then `find_julia` will find and use it (this is `~/.juliaup/bin/julia` in Linux, I suppose). So, including the path in the juliaup API is probably only useful to the extent that the link to the executable or launcher is *not* in their PATH. I don't know how often that is. My `julia` is sometimes a script that calls julia in a particular way. A package author might use `find_julia` in such a way as to avoid picking up this script.

A related question is, is there a plan for a programmatic, or at least more automated, interface for installation via juliaup? `find_julia` currently uses `jill.py`, which includes both a cli and library interface. It is very easy to use and requires almost no work on the part of `find_julia`. A crucial ingredient is that the installation paths are part of the jill.py API. In addition, I have a (not quite finished) PR to jill.py that searches for and returns the path. This would work even if the API were not published. Using juliaup in `find_julia` is currently not an option because I would have to do a lot of detective work and download the installer of the installer for the correct platform, etc. Downloading a single, cross-platform script, that would perform the installation, perhaps with environment variable control, would make juliaup a viable option. The big impediment to making jill.py universal is that mechanisms for bundling a python interpreter seem to be poor to non-existent at the moment.

**Comment by davidanthoff** [comment]
The official (and at this point stable) API is `juliaup api getconfig1`. That does provide full paths, and I think if I understand your scenario correctly that should probably work?

I can easily see that we might want to expand this API in the future. One example is what you mentioned, an official, stable API to install a specific Julia version. Another might be something where one can ask juliaup "hey, I need a Julia version from the 1.6 series, which should I use?" At the moment every client needs to figure that out by themselves from the return value that they get from ``juliaup api getconfig1`. That is not super trivial because a user might have very many versions from the 1.6 series installed at the same time.

Having said that, I'm still working on just finalizing the Mac and Linux version of `juliaup`, so right now the focus here is to get that to all work, and once we have it all in a state where it is "released", stable and (hopefully) the official way to distribute Julia, I'd be more than happy to think about more APIs that can help in scenarios like yours!

**Comment by jlapeyre** [comment]
Great, I tried `juliaup api getconfig1` and the output is what I need. This will reduce complexity and need for internal details for tools like `find_julia`. For now I can look in `~/.juliaup/bin/juliaup` on Linux. What are the corresponding paths for Windows and MacOS? If these things change later, they won't break `find_julia`, but rather just reduce the chance of finding an installation.

Regarding versions. I am currently relying on what jill.py does, which is, by default use a directory `julia-1.7`, which contains the latest `1.7.x`. You can pass a list of preferred and/or required versions to `find_julia`, but using the data correctly is only partially implemented. The `PythonCall.jl` package has some detailed Python code for finding if a Julia version matches a supplied semvar specification. I may borrow this if I find that it becomes an issue and I find the time. Of course you'd need to translate the Python or the original Julia into rust.

**Comment by davidanthoff** [comment]
> For now I can look in ~/.juliaup/bin/juliaup on Linux. What are the corresponding paths for Windows and MacOS?

I think I would just try to spawn `juliaup` without a path. The install location for `juliaup` itself _very_ much depends on how it was installed, even on the same platform, but all install methods put `juliaup` on the `PATH`. For example, when users install with the new shell script, they can pick an arbitrary install location (with `~/.juliaup/bin` as the default), when installed with `brew` it ends up in a different place, same with `AUR`, and on Windows it gets installed via the MSIX execution alias feature, where one actually shouldn't look in a specific location, but just start `juliaup` itself.

On the Julia version match, I have something similar in the VS Code extension at the moment for selecting notebook kernels. So I think for a while we'll probably just have individual clients figure this out, and then eventually we can move that logic into `juliaup`.

**Comment by jlapeyre** [comment]
> just try to spawn juliaup without a path. ...

Good, this is clearly the best option to start with.

On my system, juliaup is not on the path, but I forgot that this is exceptional. I think I explicitly answered "no" when asked. I usually try a tool before I put it on the path. Otherwise, I end up with cruft. For example, just now, I spent 10 minutes trying to find the origin of everything that `echo $PATH` shows me, and failed. I use fish and try to only change my path in the bash startup files and then import them into fish. But, some tools detect that I am using fish and add a path somewhere else, etc. 

> eventually we can move that logic into juliaup

:+1: 

I think you can close this issue. Maybe some of the loose ends mentioned here could be addressed in a new issue when the time comes.
