### ISSUE TITLE
`winget install julia -s msstore` installed the wrong thing - certainly not the Julia we know and love!

### ISSUE THREAD

**Issue by PGS62** [JuliaLang/juliaup#258]
I've used the command `winget install julia -s msstore` a few times successfully, but today on a new PC the command installed completely the wrong thing, namely an app called "Julian Date Selector".

![image](https://user-images.githubusercontent.com/18028484/156930192-639937f9-bcd4-4f5f-97eb-c3b6705ebe10.png)

![image](https://user-images.githubusercontent.com/18028484/156930253-e3b5c3cb-3114-4884-9d98-de416afef4bb.png)

**Comment by davidanthoff** [comment]
Wow, that is bad! I can reproduce it, this must be a bug on the `winget` side of things. Thanks for reporting, I'm trying to follow up with the `winget` team to figure out what is going on.

**Comment by davidanthoff** [comment]
https://github.com/microsoft/winget-cli/issues/2005

**Comment by PGS62** [comment]
I wonder if the Author of "Julian Date Selector" has just seen a gratifying uptick in his download count!
