### ISSUE TITLE
ERROR: could not load library "libjulia.1.dylib"

### ISSUE THREAD

**Issue by camilogarciabotero** [JuliaLang/juliaup#262]
Hi all,

Thanks for working on `juliaup` it is definitely a game-changer when installing and playing around with different Julia versions! 

I tried to use Julia (installed via `juliaup`) with the novel `quarto` application for scientific publishing. Simply it works by waving chunks of code from different languages with normal text. So when using chunks of Julia it fails to load the `libjulia.1.dylib` apparently. So opened an issue in the quarto repo, but the problem might scale to the installation of Julia. I'll leave the issue I posted there here:

https://github.com/quarto-dev/quarto-julia/issues/1

If there is anything else I can do to reproduce this I'll be looking forward.

**Comment by davidanthoff** [comment]
Hm, good questions. Couple of observations on the details you posted in this other issue:
- There is a message `Julia version 1.7.2 at location /Users/camilogarcia/.julia/juliaup/julia-1.7.2+0~x64/bin will be used.` I am a bit confused how quatro is finding that path? I would have thought that it would just call `julia` directly?
- `libjulia.1.dylib` should be located in the folder `/Users/camilogarcia/.julia/juliaup/julia-1.7.2+0~x64/lib/libjulia.1.dylib` (you are  on Mac, right?). Could you check whether it is there?
- The fact that you have a folder `/Users/camilogarcia/Library/Application Support/Code/User/globalStorage/julialang.language-julia/lsdepot/v1/juliaup` is a mistake, that happened early in the interaction between the VS Code extension and `juliaup`. You can (and probably should) just delete that entire folder. I don't think it is being used for anything, but if it were, then that would be a mistake in itself ;)

**Comment by camilogarciabotero** [comment]
Hi @davidanthoff 

Thanks for your reply. 

Regarding point 3: 

> The fact that you have a folder /Users/camilogarcia/Library/Application Support/Code/User/globalStorage/julialang.language-julia/lsdepot/v1/juliaup is a mistake, that happened early in the interaction between the VS Code extension and juliaup. You can (and probably should) just delete that entire folder. I don't think it is being used for anything, but if it were, then that would be a mistake in itself ;)

I just deleted and everything looks fine for the time being. Thanks.

Regarding point 2:

> libjulia.1.dylib should be located in the folder /Users/camilogarcia/.julia/juliaup/julia-1.7.2+0~x64/lib/libjulia.1.dylib (you are on Mac, right?). Could you check whether it is there?

Yes. The file is indeed in that folder as a symlink: 

```
drwxr-xr-x    - camilogarcia 10 Feb 09:46 julia
.rwxr-xr-x 190k camilogarcia  6 Feb 12:27 libjulia.1.7.dylib
lrwxr-xr-x   18 camilogarcia 10 Feb 09:44 libjulia.1.dylib -> libjulia.1.7.dylib
lrwxr-xr-x   18 camilogarcia 10 Feb 09:44 libjulia.dylib -> libjulia.1.7.dylib
```
Regarding point 3:

 >here is a message Julia version 1.7.2 at location /Users/camilogarcia/.julia/juliaup/julia-1.7.2+0~x64/bin will be used. I am a bit confused how quatro is finding that path? I would have thought that it would just call julia directly?

I don't really know how does quarto finds it... I tried to look out through their source code but was not lucky. Do you think that creating a symlink of the dynamic lib in the folder quarto is looking, might sort this out or might be inconvenient?

**Comment by davidanthoff** [comment]
Is this still an issue?
