### ISSUE TITLE
Setting Julia options from a script with the launcher

### ISSUE THREAD

**Issue by c42f** [JuliaLang/juliaup#263]
Sometimes it's useful to embed options to the `julia` executable within a script. This is particularly useful when setting options like `--compile=min` to reduce latency. For example, as done in https://github.com/c42f/RemoteREPL.jl/blob/main/bin/julia-r

Currently this can be achieved on unix by making the Julia script also a bash script, for example using the trick documented here:

https://docs.julialang.org/en/v1/manual/faq/#How-do-I-pass-options-to-julia-using-#!/usr/bin/env?

This trick depends on a separate launcher script though and won't work on windows.

Could the julia launcher which is part of `juliaup` provide a way to do this kind of thing in a cross-platform way?

**Comment by davidanthoff** [comment]
Yes, that would be pretty simple, I think. We probably just need something like channel specific configuration options, and then one could be some args that get passed?

**Comment by c42f** [comment]
> We probably just need something like channel specific configuration options, and then one could be some args that get passed?

Is the idea that you'd do something like

```
julia +fast_startup myscript.jl
```

where `fast_startup` is some channel name with options like `--compile=min`?

This could be useful but doesn't achieve the same thing as the "shell and julia" combination above which allows the script author to *embed* julia options as special comments at the top of the `.jl` file.

**Comment by davidanthoff** [comment]
Ah, I misunderstood! Yes, I was thinking about what you just described.

I guess we could also do the thing of embedding options in `.jl` files, but I think it is not entirely clear to me whether `juliaup` is the right place for that. Isn't that really something that should be in Julia itself, if we want to support it?

One thing speaking against this is that we then need to open each `.jl` file from the `julialauncher` always to look for the presence of such config values, and one very major constraint is that we need to keep the default code path in `julialauncher` as lean as possible.

Another random thought on this: does all of this suggest that it would be useful to have some sort of local folder specific config file format for Julia? For example, one could imagine a file `.juliaconfig` where users can specify various Julia config things if Julia gets invoked in that folder. Things like which Julia version, but also things like command line args.

**Comment by c42f** [comment]
> One thing speaking against this is that we then need to open each .jl file from the julialauncher always to look for the presence of such config values

> Isn't that really something that should be in Julia itself, if we want to support it?

Good points. I'm not sure what's best yet.

Putting the behavior in Julia itself should work pretty similarly. The `julia` executable would need to have a "mode line preprocessor" written in C to read the first few comment lines and extract/set options before initializing the julia runtime.

This would imply opening the input file from C, reading the first few lines and closing it again. That seems similar to doing the same thing in `julialauncher` (from  a different process, but I'm unsure that makes much difference).

Some real differences:

* Doing it in `julia` would mean it works regardless of `julialauncher` being used which seems nice.
* Doing it in `julialauncher` gives the ability to set the channel from within the script. I've wanted to pin the julia version for a particular script before so this might be useful. But this doesn't really work for public scripts committed to git — pinning the version seems more like an installation-specific consideration.

Ok, I've just re-read https://github.com/JuliaLang/Pkg.jl/issues/1962 and I think that addresses some of the same use cases, but in a much more complete way. So perhaps best to close this in favor of that issue.
