### ISSUE TITLE
Support for firewall proxy?

### ISSUE THREAD

**Issue by kbarros** [JuliaLang/juliaup#274]
My workplace requires all web traffic to go through their proxy. For example, I have configured the environment variable `$http_proxy`, and this setting is picked up by most command line utilities. Does juliaup has the capability to use this proxy setting for its connection to julialang.org? At the moment, I am seeing the error message "Connection refused". Thank you.

**Comment by DhruvaSambrani** [comment]
I do not have RUST skills, but from a precursory reading of juliaup's code and some websearching, I think the line - 

https://github.com/JuliaLang/juliaup/blob/18ea73b8d95ac02349bfb206c1438b11d7cd5803/src/operations.rs#L72

should include a new Agent with proxy support as in [the official docs](https://docs.rs/ureq/latest/ureq/#example-using-http-connect)

```rust
// Configure an http connect proxy. Notice we could have used
// the http:// prefix here (it's optional).
let proxy = ureq::Proxy::new(env::var("https_proxy"))?;
let agent = ureq::AgentBuilder::new().proxy(proxy).build();

// This is proxied.
let resp = agent.get(url).call()
```

**Comment by kbarros** [comment]
Adding to this, it looks like the [env_proxy](https://crates.io/crates/env_proxy) package could look up the appropriate environment variables according to a given `url` string.

**Comment by kbarros** [comment]
Indeed, here is where they are using `env_proxy` to get the appropriate proxy address from the target url and the environment variables:
https://github.com/rust-lang/rustup/blob/bc18467b500c8cb892cec84316b23e96207553c4/download/src/lib.rs#L350

**Comment by davidanthoff** [comment]
And maybe on Windows we should also use [WinHttpGetDefaultProxyConfiguration](https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpgetdefaultproxyconfiguration) or something similar to get the system default proxy config?

**Comment by DhruvaSambrani** [comment]
As a temporary workaround, people may find `proxychains-ng` to be of great help. Install and RTFM.

**Comment by davidanthoff** [comment]
Note to self: try to use https://docs.microsoft.com/en-us/windows/uwp/networking/httpclient (see also https://docs.microsoft.com/en-us/uwp/api/Windows.Web.Http.HttpClient?view=winrt-22621) for all downloads on Windows. If that works, it would allow us to not use `ureq` at all on Windows, so hopefully smaller binaries, and we would just pick whatever configuration for proxies/certificates/whatever a user has on Windows automatically.

**Comment by davidanthoff** [comment]
And just for completeness: env_prox seems the right choice on Mac and Linux.

**Comment by davidanthoff** [comment]
I just merged @wolthom's PR that added support for proxies, and we might add one more thing on top of that integrates even closer with default proxy configuration on Windows.

If anyone reading here has the ability to build from source and try this, please go ahead! I will probably also push a build to the prerelease channel later today for everyone else to try.

**Comment by davidanthoff** [comment]
Oh, and one more thing: if anyone finds problems with the now existing implementation, ideally please open new issues for bug reports.
