### ISSUE TITLE
let installing scripts respect `JULIAUP_SERVER`

### ISSUE THREAD

**Issue by johnnychen94** [JuliaLang/juliaup#275]
While `juliaup` itself recognizes the `JULIAUP_SERVER` environment variable, the installing script does not yet:

```julia
curl -fsSL https://install.julialang.org | sh
```

`JULIAUP_SERVER=https://mirrors.bfsu.edu.cn/julia-releases` is a public mirror server in BFSU, China.

**Comment by davidanthoff** [comment]
We have an env var called `JULIAUP_UPDATE_ROOT` that I think plays that role, see [here](https://github.com/JuliaLang/juliaup/blob/master/deploy/shellscript/juliaup-init.sh#L27). But I don't understand right now why we are using a different env var there, we should presumably just use the same one everywhere, i.e. `JULIAUP_SERVER`...

**Comment by johnnychen94** [comment]
Just verified that setting both environments works. Should I open a PR for it?

**Comment by davidanthoff** [comment]
Yes, that would be great!
