### ISSUE TITLE
Windows: Tilde as arch separator causes firewall issues

### ISSUE THREAD

**Issue by pfitzseb** [JuliaLang/juliaup#290]
Turns out that it's currently impossible to add a firewall rule for Julia installations via juliaup because of the  `~` in the dir name.
```
PS> netsh advfirewall firewall add rule name="Julia" dir=out action=allow program="%USERPROFILE%\.julia\juliaup\julia-1.7.2+0~x64\bin\julia.exe" enable=yes

The application name could not be resolved.
```
While I'm pretty sure this is a Windows bug, it would nevertheless be nice to change the convention used by juliaup.

**Comment by davidanthoff** [comment]
Agreed. My plan was to use valid semver names to identify versions, and use tilde only in channel names. I think then we should avoid this problem, plus it would be a more or less backwards compatible change.
