### ISSUE TITLE
juliaup-init brings up interactive prompt when called with -y flag

### ISSUE THREAD

**Issue by colinthart** [JuliaLang/juliaup#300]
I have downloaded `juliaup-init` and invoke it with the `-y` flag

```
curl -fsSL https://install.julialang.org >> juliaup-init
chmod +x juliaup-init
./juliaup-init -y
```

My usage of the `-y` flag is based on the help message:
```
juliaup-init: the installer for juliaup

USAGE:
    juliaup-init [FLAGS] [OPTIONS]

FLAGS:
    -y, --yes               Disable confirmation prompt.
        --no-add-to-path    Don't add to user PATH environment variable
    -h, --help              Prints help information

OPTIONS:
    -p, --path              Custom install path
```

However, the installer is still launched in interactive mode.

I believe this is not the intended behavior.  If it is, is there another way to install juliaup by a shell script without user interaction?

Thank you.

**Comment by colinthart** [comment]
Possibly related to [#218](https://github.com/JuliaLang/juliaup/issues/218)

**Comment by cunha** [comment]
Non-interactive installation by first downloading the `sh` script and then executing the script with command-line parameters would be useful for sysadmins. It seems there are two steps needed to achieve this:

* The `sh` script should pass command-line parameters to the installer.
* The installer should parse command line parameters. (Maybe moving the fields inside `struct InstallChoices` into `struct Juliainstaller` and adding `clap` derives would address this.)

**Comment by davidanthoff** [comment]
Yes, this is a dup of #218, and yes, this is just not finished yet :)
