### ISSUE TITLE
Feature request: ability to build Julia from source with `juliaup add X.x.p --build` or similar

### ISSUE THREAD

**Issue by AstroFloof** [JuliaLang/juliaup#305]
Imo would be a nice feature for those who like to build everything with their own customizations and compiler tweaks, such as users of Gentoo Linux and its derivatives. Pyenv is a good example of this already in action, although that's written almost entirely in shell.

**Comment by StefanKarpinski** [comment]
You can use `juliaup link $name $path` to make juliaup aware of whatever custom built Julia binary you want. Does that cover what you're thinking of or am I missing the point?

**Comment by davidanthoff** [comment]
I think we should stay out of _building_ Julia with `juliaup`, that just opens such a gigantic can of worms that I'm not really convinced we should go there. We _are_ going to add the ability to install nightly builds, and I think that in combination with the `link` option is kind of good enough?

**Comment by AstroFloof** [comment]
Fair enough
