### ISSUE TITLE
Self update feature error on x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by darleybarreto** [JuliaLang/juliaup#333]
Hi,

I was trying to build `main` with `x86_64-pc-windows-gnu`. [This](https://github.com/JuliaLang/juliaup/blob/main/src/command_selfuninstall.rs#L8) line gives the (summarized) error
```rust
error[E0432]: unresolved import `crate::command_config_symlinks::run_command_config_symlinks`
```

**Comment by darleybarreto** [comment]
Self updating on Windows is only available with `windowsstore` feature.

**Comment by davidanthoff** [comment]
Yeah, on Windows the only option that is really supported right now is msvc and then without any of the self update features, those just generally don't work on Windows (yet).

**Comment by davidanthoff** [comment]
See https://github.com/JuliaLang/juliaup/pull/346.
