### ISSUE TITLE
Installer instructions say minutes, summary says seconds

### ISSUE THREAD

**Issue by kescobo** [JuliaLang/juliaup#344]
Just went to try juliaup for the first time, did a custom install, and noticed a discrepancy between the instructions and the report.

[Here](https://github.com/JuliaLang/juliaup/blob/f58eb1239141f293b75bb5dca6fbbe91de57c09e/src/bin/juliainstaller.rs#L44), it asks about *minutes* between checks, but [here](https://github.com/JuliaLang/juliaup/blob/f58eb1239141f293b75bb5dca6fbbe91de57c09e/src/bin/juliainstaller.rs#L140) it says *seconds*. Both report 1440.

![image](https://user-images.githubusercontent.com/3502975/181782747-84ee7e20-146f-452d-a8e9-01f4a96e2c82.png)

**Comment by kescobo** [comment]
I'm happy to open a PR, but know nothing about rust, so not sure how too look which one is actually intended :-)

**Comment by LF-Flores** [comment]
From what I can see in the [crontab configuration](https://github.com/JuliaLang/juliaup/blob/f58eb1239141f293b75bb5dca6fbbe91de57c09e/src/operations.rs#L336), the intended use is **minutes**. It also says in [the comment here](https://github.com/JuliaLang/juliaup/blob/0966d99ae5ff9f202ec7cb4283d70b5da9388f02/src/bin/juliaup.rs#L115) that it should be in minutes. 

I'll make a pull request with the change if everything's okay :)
