### ISSUE TITLE
Consider supporting αcτµαlly pδrταblε εxεcµταblε

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/juliaup#350]
https://justine.lol/ape.html

https://justine.lol/cosmopolitan/

I've been thinking of trying this for Julia (will likely encounter some issues, since it's a complex project, not just C), but it might be even easier for Juliaup, that is for rust. I know it's been done for rust and some other languages (e.g. Python).

It might be a simple fix for your or @DilumAluthge, older glibc problem, since you then need none of it #321.

What's the oldest glibc Julia supports otherwise (and what julia up supports)?

This might simplify Linux setup (and getting it to work with just one-file binary download).

EDIT: Well feel free to close again... I see I suggested in the past (I was thinking of this now for the glibc problem and didn't recall, so also consider keeping issue open (for others, it's a simple recompile) or implement): https://github.com/JuliaLang/juliaup/issues/139#issuecomment-913930093

**Comment by PallHaraldsson** [comment]
I was trying to look up Rust compilation info. I didn't find it right away (could look more if you want), but found:

https://news.ycombinator.com/item?id=26103769
>... What Cosmopolitan does, it does really well. No other C library is able to target multiple operating systems and all the x86 microarchitectures. ...

Note the binary would run on all your supported platforms (including Windows, typical .exe, not sure about the Windows Store though, so if not you would have one build for it, and one for the rest, Linux, FreeBSD, Alipine with musl, without glibc since neither used).

It would also support M1 Apple Macs, or should despite only supporting x86, because of Rosetta. That wouldn't mean the actual downloaded julia would use Rosetta, only juliaup, and that should be fine.

When you would get one platform to work, say Linusx, it would assume Linux paths, even on Windows, so I suppose for Windows you would need some OS detection, and simple path substitution (if you would use this build for Windows, otherwise no changes to your code).

So one gain, is simplifying the build of your code to 1 or max 2 supported platforms... instead of 5 or 6 I can recall.

**Comment by PallHaraldsson** [comment]
Even disregarding the portability "solution" across Windows, MacOS, Linux and FreeBSD might be warranted, as different Linux distros have different considerations without this (and even some code for older Ubuntu will not run on newer Ubuntu...):

I think there's some Rust build info there, and more info:
https://users.rust-lang.org/t/build-once-run-anywhere-cosmopolitan-libc/66528

>Reimplementing libc is fine on Linux where the kernel syscall interface is well documented and guaranteed to be stable but that isn't true on other OS's. On Windows for example, bypassing "libc" isn't supported and syscall numbers can change at any time including a routine Windows update.

I wanted to quote that to not give a too optimistic impression. I still find it very unlikely that the few Windows syscall numbers you would actually use aren't stable by now (and I believe the author has written something about it, to that effect). It is a cool project, and at least non-GUI stuff should be stable (and if I recall GUI programs also made with this).

**Comment by PallHaraldsson** [comment]
It might be good to know (independently of this), there's available a Rust-to-C compiler: https://github.com/thepowersgang/mrustc

[Also for other wy c2rust: see https://users.rust-lang.org/t/can-rust-compile-to-c-and-c/47434/2 ]

so then compiling from Rust-C, then use GCC (if not direct Rust build info), and the default info:
https://justine.lol/cosmopolitan/

**Comment by DilumAluthge** [comment]
> What's the oldest glibc Julia supports otherwise (and what julia up supports)?

For Julia, it depends on the architecture: https://github.com/JuliaPackaging/Yggdrasil/blob/3aa25f9eb060cfc435583f280e675396d089055e/0_RootFS/gcc_common.jl#L245

**Comment by davidanthoff** [comment]
One major meta goal is to keep the size of `julialauncher` as small as possible so that it starts fast. I don't think this would help here.

We have a solution for the glibc problem, we will just statically link a libc going forward, that is tracked somewhere here.

**Comment by xgdgsc** [comment]
Is threre direct link to musl binary? I built it myself and it works. I thought it might be a good idea to provide that as the default for linux users so they won' t see glibc issues.

**Comment by DilumAluthge** [comment]
This work is still in progress. One option, as mentioned above, is to statically link musl, but there are various challenges with using musl. An alternative approach is to use the same toolchain that we use for building Julia itself to build Juliaup. When building Julia, we link to old glibc versions (e.g. on x86_64, Julia supports glibc as old as 2.12.2). If we can use the same toolchain to build the Linux binaries of Juliaup, then Juliaup will be able to support the same glibc versions as Julia itself.

Anyway, it will probably be a while before we start distributing Juliaup binaries that are built like that.
