### ISSUE TITLE
Port to Mac

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#37]
In an ideal world we could create a Mac app store submission that ships the launcher and juliaup and have everything work on Mac as well.

The launcher is just a small C++ program that probably could be made cross-platform fairly easily. Juliaup is written in Julia in any case.

Main question is to figure out how one can package something as a Mac app store submission, really.

**Comment by davidanthoff** [comment]
Another question to figure out is whether one can submit apps to the Mac app store that do not run inside a sandbox because that would really be a minimum requirement.

If the whole app store direction turns out to be a dead-end on Mac, I guess one could also consider that brew should install Juliaup by default if a user installs julia via brew?

**Comment by davidanthoff** [comment]
The `rust` branch works on Linux, and it should be simple to also get it to work on Mac. The problem I have right now is that there doesn't seem to be a `tar.gz` file for Mac that I could just extract to `./julia/juliaup/julia-1.5.2+0~x64` like I'm doing it on Windows and Linux.

Can on in general just extract a tar ball on Mac and then run binaries from there? Or do we have to use an entirely different strategy there?

**Comment by staticfloat** [comment]
> The problem I have right now is that there doesn't seem to be a `.tar.gz` file for Mac 

There are, in fact!  Just replace `.dmg` with `.tar.gz` and you'll get it.  We don't offer it for download on the webpage, since most users wouldn't want it and might get confused, but for infrastructure people like us, it's very helpful to have it around.

Example: https://julialang-s3.julialang.org/bin/mac/x64/1.6/julia-1.6.2-mac64.tar.gz

**Comment by davidanthoff** [comment]
Perfect, with that the `rust` branch works on Mac as well :)
