### ISSUE TITLE
RC4 doesn't show up (MacOS)

### ISSUE THREAD

**Issue by roland-KA** [JuliaLang/juliaup#385]
On my MacOS-installation RC4 (which should be available since about one week) doesn't show up. It's not listed when I call `juliaup list` and `juliaup update rc` does nothing (I have currently RC3 installed).

On a Windows system which I tried yesterday, it works fine.

**Comment by MatthijsBlom** [comment]
Which `juliaup` version are you on? RC4 is only listed by versions 1.7.20 and up.

**Comment by roland-KA** [comment]
Ah, I was on 1.6.12. After updating it works. Thanks!

... but is it really a good idea to make the availability of Julia versions dependent on the version of the installer? In order to manage Julia versions I use `juliaup` ... and then I have to mange `juliaup` versions (using another tool?!) in order to manage Julia versions. That sounds somehow like an endless story 😬.

**Comment by MatthijsBlom** [comment]
Yes, this comes up again and again. See #326.

**Comment by davidanthoff** [comment]
The TODO for me is already being tracked by other issues, so closing this one here.
