### ISSUE TITLE
juliainstaller fails on NixOS

### ISSUE THREAD

**Issue by benide** [JuliaLang/juliaup#386]
When I run `curl -fsSL https://install.julialang.org | sh` on NixOS, the only output is the following:

```
info: downloading installer
main: line 449: /tmp/tmp.21Sq6CljVh/juliainstaller: No such file or directory
```

I'm not really sure what info to give other than that since it's failing so early.

**Comment by davidanthoff** [comment]
That is this line https://github.com/JuliaLang/juliaup/blob/d184c497b85861df8ee3db7f94c8bc3200bc2729/deploy/shellscript/juliaup-init.sh#L449. I'm not very familiar with shell scripting, so not sure what exactly the problem might be.

Note that you can't run the file that is stored here on GitHub directly, but you _can_ just download the file from https://install.julialang.org and then try and see what the problem in that code is.

Any help would be appreciated!

**Comment by benide** [comment]
I tried downloading the file from https://install.julialang.org and running it. It gives the same error.

It looks like that line is only being called a few times, so I think it must be failing here:

https://github.com/JuliaLang/juliaup/blob/d184c497b85861df8ee3db7f94c8bc3200bc2729/deploy/shellscript/juliaup-init.sh#L140

but this is strange because that would mean it's getting through these lines successfully and not running the stuff inside the `if`:

https://github.com/JuliaLang/juliaup/blob/d184c497b85861df8ee3db7f94c8bc3200bc2729/deploy/shellscript/juliaup-init.sh#L122-L129

I don't see how that could actually happen, but since `ignore` isn't called before then this must be what's happening.

**Comment by benide** [comment]
Update: it is definitely failing on https://github.com/JuliaLang/juliaup/blob/d184c497b85861df8ee3db7f94c8bc3200bc2729/deploy/shellscript/juliaup-init.sh#L134

I downloaded the file https://julialang-s3.julialang.org/juliaup/bin/juliainstaller-1.7.20-x86_64-unknown-linux-gnu directly, then ran `chmod u+x juliainstaller-1.7.20-x86_64-unknown-linux-gnu`, then tried to run it and got the output

```
bash: ./juliainstaller-1.7.20-x86_64-unknown-linux-gnu: No such file or directory
```

So it's something in the actual juliainstaller file, and apparently the script is actually working perfectly.

**Comment by davidanthoff** [comment]
I'm wondering whether this might somehow be related to the glib issue? We are linking against a fairly new glib version, and if that is not present on your system that binary will not run. We are trying to find a way to compile against older glib versions, so maybe that would help here..

**Comment by benide** [comment]
My glibc version is 2.35, so I don't think so. Just to be up front: NixOS tends to be pretty different, but I don't really know enough about the specifics to be all that helpful. Whatever the problem is, it might end up being something the team doesn't care much about honestly.

**Comment by uncomfyhalomacro** [comment]
> When I run `curl -fsSL https://install.julialang.org | sh` on NixOS, the only output is the following:
> 
> 
> 
> ```
> 
> info: downloading installer
> 
> main: line 449: /tmp/tmp.21Sq6CljVh/juliainstaller: No such file or directory
> 
> ```
> 
> 
> 
> I'm not really sure what info to give other than that since it's failing so early.

I haven't touched NixOS in a while so bear in mind that this might not be true anymore (but you can always check their Wiki). I don't think you can run binaries that are not from the nix store _by default_. try running the installer for rustup or some binary not from the nix store and you will get what I mean.

**Comment by benide** [comment]
Huh, you're absolutely right. I had never noticed, I guess because there is so much in the nix store. There was a request to add juliaup to the nix store (https://github.com/NixOS/nixpkgs/issues/184186), but I think (as mentioned here https://github.com/NixOS/nixpkgs/pull/184592) that this should be done in home-manager because it just doesn't really make sense in the nix store as far as I can tell. I was hoping to get around it by just using as if I wasn't on NixOS. I guess I should try to learn how to package it in home-manager then.

In any case, this is definitely not a juliaup issue. Sorry about that!

**Comment by raju-bitter** [comment]
The install runs through on NixOS 6.1.56:
```
[raju@nixos:~]$ curl -fsSL https://install.julialang.org | sh

info: downloading installer
Welcome to Julia!

This will download and install the official Julia Language distribution
and its version manager Juliaup.

Juliaup will be installed into the Juliaup home directory, located at:

  /home/raju/.juliaup

The julia, juliaup and other commands will be added to
Juliaup's bin directory, located at:

  /home/raju/.juliaup/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:



Julia will look for a new version of Juliaup itself every 1440 minutes when you start julia.

You can uninstall at any time with juliaup self uninstall and these
changes will be reverted.

✔ Do you want to install with these default configuration choices? · Proceed with installation

Now installing Juliaup
Installing Julia 1.9.3+0.x64.linux.gnu
Configured the default Julia version to be 'release'.
Julia was successfully installed on your system.

Depending on which shell you are using, run one of the following
commands to reload the PATH environment variable:


```
Here the PATH does not get set, but using absolute path to `juliaup` I was able to install Julia 1.10:
```
[raju@nixos:~]$ .juliaup/bin/juliaup add 1.10
Installing Julia 1.10.0-beta3+0.x64.linux.gnu
```
