### ISSUE TITLE
Update JuliaLang to Explain/Recommend JuliaUp

### ISSUE THREAD

**Issue by mrufsvold** [JuliaLang/juliaup#395]
I am working with my company's ITS to get the Windows Store version of Julia (and JuliaUp) approved for our work computers. The [Juliaup Presentation ](https://www.youtube.com/watch?v=14zfdbzq5BM) from this year's JuliaCon was a pretty strong endorsement that Juliaup is the best way to install and manage Julia versions but having that in writing somewhere would be very helpful evidence for getting people who are not in-the-loop to understand why they should work on getting the Windows Store version approved, not just the download link on JuliaLang.org.

Does anyone have the capacity to throw an extra paragraph on the [Julia download page](https://julialang.org/downloads/platform/#windows) to say it is a good/ the best/ a recommended way to install Julia?

Edit: I know it's a little silly since Juliaup is mentioned by name on the page already. I'm just dealing with folks who are especially security conscious and are going to default to 'no' unless there is a very good reason to do otherwise.

**Comment by cmichelenstrofer** [comment]
The presentation mentioned that this will be the default way to install Julia, but that hasn't happened yet. Is that still the plan?

**Comment by StefanKarpinski** [comment]
It is the plan pending @davidanthoff feeling that it is ready to become the official means of installing Julia.

**Comment by mrufsvold** [comment]
See [this conversation](https://discourse.julialang.org/t/official-juliaup-recommendation/86994) on discourse for more context.

**Comment by davidanthoff** [comment]
My thoughts on this are https://github.com/JuliaLang/www.julialang.org/issues/1922, closing this for now.
