### ISSUE TITLE
Error: The Julia launcher failed to determine the command for the `1.8.0` channel.

### ISSUE THREAD

**Issue by giordano** [JuliaLang/juliaup#405]
```console
% julia +1.8.0
Error: The Julia launcher failed to determine the command for the `1.8.0` channel.

Caused by:
    Invalid channel specified
% julia +1.8
Error: The Julia launcher failed to determine the command for the `1.8` channel.

Caused by:
    Invalid channel specified
```
I'm sure I'm missing something, but the `1.8.0` or `1.8` channels look very much valid to me, and also according to `juliaup list` itself:
```console
% juliaup list | grep -e '1.8.0[^+.~-]'   
 1.8.0            1.8.0+0.x64       
% juliaup list | grep -e '1.8[^+.~-]'  
 1.8              1.8.1+0.x64
```

**Comment by MatthijsBlom** [comment]
The channel is valid, but it is not installed. `juliaup status` lists all installed channels. `juliaup list` lists all channels, installed or no.

The error message could probably use some clarification.

**Comment by carstenbauer** [comment]
I think this is related to #115

**Comment by davidanthoff** [comment]
I'm assuming that @MatthijsBlom explanation is correct, if not, please reopen.

**Comment by giordano** [comment]
> The error message could probably use some clarification.

**Comment by davidanthoff** [comment]
Yes, that is https://github.com/JuliaLang/juliaup/issues/115.
