### ISSUE TITLE
juliaup windows exe download

### ISSUE THREAD

**Issue by AbhimanyuAryan** [JuliaLang/juliaup#413]
where can I get juliaup windows .exe instead of downloading it from Microsoft Store?

**Comment by davidanthoff** [comment]
On Windows the only supported distribution at the moment is via the Windows Store. I don't plan to distribute individual binaries at the moment as that would essentially defeat the entire auto-update idea. What is the use-case you are trying to solve?

**Comment by AbhimanyuAryan** [comment]
I was thinking of removing bloatware and default Microsoft apps from Windows. Block all sorts of Microsoft telemetry that will also kill Microsoft store and outlook using WPD.app, policies and win registry

I was wondering if I can get JuliaUp via some 3rd party(non-Microsoft) place

**Comment by ViralBShah** [comment]
I personally don't use the windows store for anything. So I had to literally figure it out just for `juliaup`. I would much rather just download it from julialang.org and update it infrequently. 

I do agree that the windows store is more convenient now that I have it set up.

**Comment by ViralBShah** [comment]
Closing as dup of #343

**Comment by davidanthoff** [comment]
@ViralBShah I think `winget install julia -s msstore` should work on all Windows versions now, out-of-the box without the need to interact with the store. We could also remove the non-store version of Julia from `winget` and at that point the command `winget install julia` would do the trick.

Another option is that once we make this the default we have a link that directly opens the store on the correct app page. So someone would go to julialang.org/install, click one link and then click "Install" and that would be it. I think that would work, but not entirely sure.

**Comment by MatthijsBlom** [comment]
> I think `winget install julia -s msstore` should work on all Windows versions now, out-of-the box without the need to interact with the store.

I tried it, but&hellip;

```
> winget install julia -s msstore
Found Julia [9NJNWW8PVKMN] Version Unknown
This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.
[snip]
Verifying/Requesting package acquisition...
Verifying/Requesting package acquisition failed: no store account found
```

**Comment by MatthijsBlom** [comment]
Yes, this is on a non-linked system.

**Comment by ViralBShah** [comment]
You know I did get it through the `winget install julia -s msstore` approach - but I thought that meant that I was actually installing through the windows store and it used something I had stored on my computer for the Windows Store login or something.
