### ISSUE TITLE
Feature Request : copy startup.jl when updating

### ISSUE THREAD

**Issue by gsoleilhac** [JuliaLang/juliaup#418]
Hi, 

I just updated from 1.8.1 to 1.8.2 and the whole juliaup/julia-1.8.1+0.x64 folder is gone, with my startup.jl script.

I think copying that file over to the new folder would be a reasonable behaviour, or maybe show a prompt asking if we want to keep that file ?

**Comment by carstenbauer** [comment]
Maybe I'm misunderstanding but if you simply put your `startup.jl` into `~/.julia/config` it will always be used (irrespective of what juliaup does and which julia version is used).

**Comment by davidanthoff** [comment]
As a user you should treat the whole `.julia/juliaup` folder as read-only, or rather all its content being managed by Juliaup. For user provided startup files, use the location that @carstenbauer recommended.
