### ISSUE TITLE
Idea: show that user can run `juliaup` from within Julia

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/juliaup#43]
One thing that a user might stumble on is how to run `juliaup` commands without having to launch a new command window. They may not realize shell commands can by run from within Julia.

So something like (paraphrased message):

```
Julia version 1.6.1 is available. Run:

  juliaup update

to install Julia 1, the latest Julia version for the current channel.

This command may be run within Julia by typing a semicolon (;) to access the shell prompt.
```

**Comment by davidanthoff** [comment]
Oh wow, I didn't even consider that one can run `juliaup` from within `julia`! But actually, that does of course work, at least I think everything except deleting the currently running Julia version should work.

I guess one could even think about a `juliaup` repl mode down the road...

**Comment by KronosTheLate** [comment]
Changing the message should be quick easy enough. Why is this still an issue, almost 8 months later?

**Comment by BioTurboNick** [comment]
@KronosTheLate - Presumably it wasn't a priority. And it's a nice-to-have thing, not a necessity. I'm sure a PR would be welcome if you feel strongly enough about it :-)

**Comment by MatthijsBlom** [comment]
Wouldn't `julia` need to be re-run after updating?

**Comment by eahenle** [comment]
Having done this, I wouldn't recommend it to users.  I wouldn't *discourage* anyone from doing it, but I wouldn't *advertise* it either.  After doing this, the user has to restart Julia, and after doing that, the first time `Pkg.update()` runs, the session crashes.  Edges are just too rough, IMO--better to have people do `juliaup` from the OS.

**Comment by BioTurboNick** [comment]
Fair enough! Willing to close this if David concurs.
