### ISSUE TITLE
Cannot execute juliainstaller

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/juliaup#450]
First time trying juliaup, attempted to install in on a server (with gentoo). The result is:
```zsh
╰─$ curl -fsSL https://install.julialang.org | sh


info: downloading installer
Cannot execute /tmp/tmp.WgttSEbBvc/juliainstaller.
Please install the files to a location where you can execute binaries.
```
The server policy is to mount the `/tmp` filesystem as noexec, so makes sense that it couldn't execute that file.

I tried copying `/tmp/tmp.WgttSEbBvc/juliainstaller` to another location to run it, but the file doesn't seem to even exist.

What else can I do to install juliaup?

**Comment by davidanthoff** [comment]
Maybe we need to add a command line argument for the shell script that allows one to specify a temporary location where the `juliainstaller` should be put? In a case like yours one could then simply specify an alternative location that is different than `/tmp`. Would that work?

**Comment by fingolfin** [comment]
Issue #673 is related: there `curl` can't download to `/tmp`.
