### ISSUE TITLE
Not sure if this is a typo or not

### ISSUE THREAD

**Issue by uncomfyhalomacro** [JuliaLang/juliaup#482]
**OS**: openSUSE Tumbleweed x86_64
**Juliaup**: Version 1.8.7 (pre-release)

## Issue

Running `juliaup add release` produces this output:

```
❯ juliaup add release
Installing Julia 1.8.3+0.x8664.linux.gnu (x64).
  Downloading: [==>                 ] 14.23 MiB/124.01 MiB eta: 8m   
```

Julia 1.8.3+0.x8664.linux.gnu seems to look kind of awkward to read.

**Comment by davidanthoff** [comment]
Yeah... I'm trying to use valid semver names in more places, and so this is my attempt at squishing platform triplets into the build part of a semver. Both `-` and `_` are not valid there... I guess one thing we could do is just replace the `x8664` part with something else. Would that address the weirdness here?

**Comment by davidanthoff** [comment]
Alright, I'm changing the semver strings that we use here to `1.8.3+0.x64.linux.gnu` and `1.8.3+0.x86.linux.gnu` (also for all other platforms). That brings it in line with the writing we use in the channel names.

We can _also_ (later) decide to display these semver things in a nicer way, for example we can strip out the build info entirely and then just display the arch in parentheses or something like that.

**Comment by uncomfyhalomacro** [comment]
I am not sure about following `semver` nor I am knowledgeable on that area. `rustup` for example, does not use `semver` for managing toolchains. They just use the versions from the toolchains through regex. And my guess is that they only use semver for sorting versions.

**Comment by davidanthoff** [comment]
Using semvers is very convenient internally. The question really just is how do we best display those to the user. For now I made the change I just described. I think going forward we could also start to output them in a more user friendly way if that seems useful.

**Comment by davidanthoff** [comment]
I think this is ok for now, right?

**Comment by uncomfyhalomacro** [comment]
ye. it should be alright for now. thank you!
