### ISSUE TITLE
Channel name is "1"

### ISSUE THREAD

**Issue by aviks** [JuliaLang/juliaup#52]
The message on starting julia after getting it from the store is

```
The latest version of Julia in the 1 channel is Julia 1.6.1
```

The channel name should probably be changed to `release` or something like that?

**Comment by davidanthoff** [comment]
Yes, agreed, I want to add a whole bunch of additional name channels, see [here](https://github.com/JuliaLang/juliaup/issues/14). And yes, the default should not be `1`, but rather `release` or `latest` or whatever.

One thing that is not clear to me right now is what the "canonical" name for "latest stable" release is. It seems to me that all the CI systems don't have a name for that anymore? I'll probably just ask on slack :)

**Comment by davidanthoff** [comment]
I went with `release` as the default channel name now.
