### ISSUE TITLE
typo in the error msg of `juliaup update`

### ISSUE THREAD

**Issue by shayandavoodii** [JuliaLang/juliaup#535]
```
C:\Users\Shayan>juliaup update
Error: Failed to uopdate versions db.

Caused by:
    0: Failed to download current version db version.
    1:
    2: The connection with the server was reset (0x80072EFF)
```
Edit the `uopdate` to `update`

**Comment by LilithHafner** [comment]
Thanks for spotting this! If you'd like to fix it yourself, you can make a PR that edits these files:
https://github.com/JuliaLang/juliaup/edit/main/src/command_selfupdate.rs
https://github.com/JuliaLang/juliaup/edit/main/src/command_update.rs
(I found those files from [this search page](https://github.com/JuliaLang/juliaup/search?q=uopdate))

**Comment by shayandavoodii** [comment]
> you'd like to fix it yourself, you can make a PR that edits these

Are you saying that I can make my first-ever contribution?

**Comment by shayandavoodii** [comment]
Fixes https://github.com/JuliaLang/juliaup/issues/535 and closes https://github.com/JuliaLang/juliaup/pull/537
