### ISSUE TITLE
Picking up juliaup in an existing depot not working as expected

### ISSUE THREAD

**Issue by thofma** [JuliaLang/juliaup#553]
I wanted to give https://github.com/JuliaLang/juliaup/pull/510 a try. I have juliaup stuff in my default depot:
```
 ~  ls ~/.julia/juliaup
julia-1.8.5+0.aarch64.apple.darwin14 juliaup.json                         versiondb-aarch64-apple-darwin.json
```
I want it to use this when prepending `/tmp/a` to the `DEPOT_PATH`. So I do
```
export JULIA_DEPOT_PATH="/tmp/a:"
```
(the directoy `/tmp/a` does not exist). But then juliaup wants to populate `/tmp/a/juliaup` and starts downloading the binary:
```
  ~  julia
Installing Julia 1.8.5+0.aarch64.apple.darwin14
  Downloading: [>                   ] 2.85 MiB/102.59 MiB eta: 20s
```
which is unexpected. It should pick up the thing in `~/.julia/juliaup` if I understand it correctly.

@jakobnissen am I using this correctly?

P.S.: This is
```
 ~  juliaup --version
Juliaup 1.8.16
```
on OSX as you might have guessed.

**Comment by jakobnissen** [comment]
I can't reproduce. I'll try to look deeper into it tomorrow

**Comment by jakobnissen** [comment]
I have tried looking into it today, but can't find anything. I can't reproduce on Linux, and can't see how MacOS would behave differently for the relevant code.

**Comment by thofma** [comment]
Same happens for me on linux.

**Comment by jakobnissen** [comment]
Here's what happens when I use Juliaup 1.8.16 on Linux:
https://asciinema.org/a/aUrDqzz0IeVtwYRTycvGI9Nnq

**Comment by thofma** [comment]
Not an issue anymore.
