### ISSUE TITLE
julia.exe not located automatically by VSCode

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaLang/juliaup#56]
The order of thing:
* I had julia installed, and the `bin/julia.exe` manually typed into the settings for the julia extension for VSCode
* I uninstalled julia with chocolatey, but kept my .julia folder
* I checked that julia was removed from path - it was
* I installed julia via the microsoft store - worked great
* Checked that julia was in my path - it was
* I updated to 1.6.1 with juliaup update from a terminal
* I opened up a .jl script in VSCode

At this point I am notified that VSCode has actually NOT updated the location of the julia.exe. I was able to find it in `C:\Users\densb\AppData\Local\Microsoft\WindowsApps\JuliaComputingInc.Julia_b0ra4bp6jsp6c`, and manually type that is as the location of the excecutable in the settings for the julia extension for VSCode.

This was suppoed to be automated, right?

**Comment by davidanthoff** [comment]
So what you need to do there is just completely remove the `julia.executablePath` setting in the VS Code settings. The default for that in VS Code is empty, and if that is the case everything should automatically work. But if you have something configured for that setting, then we don't update that and you need to make sure the setting is correct.

I would not configure the location you have set now, that is very much an implementation detail. Just have an empty value for that setting or remove it entirely and things should work.
