### ISSUE TITLE
Add SOCKS5 support

### ISSUE THREAD

**Issue by shayandavoodii** [JuliaLang/juliaup#575]
I installed Julia v1.8.5 using Juliaup. I live in Iran, and nowadays we are experiencing massive internet censorship that affects our activities. In the case of Julia, we can't update our registry easily. Most VPNs don't work anymore, and we can barely use them. But the TOR protocol still works (although it's super slow, it works). Can you provide an option to set socks5 proxy in Julia Pkg manager for this problem? For example, I can update Julia to the newest version available by connecting to TOR using the TOR Browser and then setting a proxy in the windows' command prompt (or the Terminal) by entering `set http_proxy=socks5://127.0.0.1:9150` and then entering the `juliaup update` command. So I wonder if you can provide such a tool? 😔
Thank you.

**Comment by shayandavoodii** [comment]
Oh, sorry. I thought I opened the Julia repository. How can I delete this issue here?

**Comment by StefanKarpinski** [comment]
You'd need support for this on both juliaup and julia itself to make everything work. Julia uses libcurl, which certainly supports proxies if you configure it correctly, although I haven't tried that so I'm not sure what it would take. Juliaup is a completely different stack written in Rust, and while I'm sure a socks5 proxy could be supported I'm again not sure what it would take.

**Comment by davidanthoff** [comment]
On Mac/Linux we use https://inejge.github.io/env_proxy/env_proxy/index.html for proxy configuration, I think whatever is supported there should work for Juliaup as well. On Windows Juliaup uses the standard win32 API for downloads, so whatever proxy configuration you have for your Windows system will be used by Juliaup as well.

**Comment by StefanKarpinski** [comment]
It would be good if there was a single way to configure a proxy for both juliaup and julia.

**Comment by shayandavoodii** [comment]
> On Windows Juliaup uses the standard win32 API for downloads, so whatever proxy configuration you have for your Windows system will be used by Juliaup as well.

Exactly! As I mentioned:
>  can update Julia to the newest version available by connecting to TOR using the TOR Browser and then setting a proxy in the windows' command prompt (or the Terminal) by entering set http_proxy=socks5://127.0.0.1:9150 and then entering the juliaup update command.

So, Juliaup can handle this using the system configuration for updating Julia. But the updating packages within Julia wouldn't is my concern here! In this situation (which is going to get worse even 😔 specifically in Iran) ability to set a proxy can be promising.

**Comment by davidanthoff** [comment]
> It would be good if there was a single way to configure a proxy for both juliaup and julia.

I think on Mac/Linux that is the case.

On Windows I think the behavior of Juliaup is the one that one would really want, i.e. if there is a system proxy configured it should just be used. I think ideally the package manger would do the same. My understanding is that libcurl doesn't support that right now (https://github.com/curl/curl/issues/3965), though. One could probably modify Download.jl to extract system proxy info on Windows, the link has a number leads on how that would look.

Another option would be to teach Juliaup on Windows about the proxy env variables that Pkg.jl currently uses. I'm not a huge fan, though, for two reasons: 1) this is really a very non-Windows way of doing things, and it is very hard to imagine a system where the system configuration is not already all we need, 2) I'm using the standard Windows API right now for downloading, and they are _extremely_ simple and easy, super reliable and handle absolutely everything for us out-of-the box (proxy, certificates etc). Not having to deal with all of these complications at all strikes me as a major plus.

**Comment by davidanthoff** [comment]
I have a PR that adds SOCKS5 support on Mac/Linux. I think at that point Juliaup essentially supports all kinds of proxies on all kind of platforms.
