### ISSUE TITLE
`juliaup link` doesn't seem to `abspath`

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/juliaup#577]
if you provide a relative path when linking a new binary, juliaup doesn't convert it to absolute first, making the link basically useless.

it should be fine to do this, right?

**Comment by davidanthoff** [comment]
Yes, we could just use the current working folder and append the relative path, right?

**Comment by StefanKarpinski** [comment]
Looking at https://stackoverflow.com/questions/30511331/getting-the-absolute-path-from-a-pathbuf, it seems like https://crates.io/crates/path-absolutize might be the thing to use? Kind of surprising this isn't built in.
