### ISSUE TITLE
Updating to 1.9.0-beta4 broke things for me

### ISSUE THREAD

**Issue by tbeason** [JuliaLang/juliaup#581]
I knew a new beta release was available so I did `juliaup update`. It installed the new beta and also 1.8.5 since I had not run this for a while. I also switched my default to be the new beta since I have mostly been using beta3 lately anyway (with `julia +beta`).

Output of `juliaup status`
```
 Default  Channel  Version                        Update
---------------------------------------------------------
       *  beta     1.9.0-beta4+0.x64.w64.mingw32
          release  1.8.5+0.x64.w64.mingw32
```

But, starting REPL with `julia` loads 1.8.5 (when it should load beta) and using `julia +beta` results in an error:
```
PS C:\Users\beasont> julia +beta
ERROR: SystemError: opening file "C:\\Users\\beasont\\+beta": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base .\error.jl:176
  [2] #systemerror#80
    @ .\error.jl:175 [inlined]
  [3] systemerror
    @ .\error.jl:175 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base .\iostream.jl:293
  [5] open
    @ .\iostream.jl:275 [inlined]
  [6] open(f::Base.var"#387#388"{String}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base .\io.jl:382
  [7] open
    @ .\io.jl:381 [inlined]
  [8] read
    @ .\io.jl:462 [inlined]
  [9] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base .\loading.jl:1484
 [10] include(mod::Module, _path::String)
    @ Base .\Base.jl:419
 [11] exec_options(opts::Base.JLOptions)
    @ Base .\client.jl:303
 [12] _start()
    @ Base .\client.jl:522
```

I am on Windows 10.

**Comment by davidanthoff** [comment]
To me this looks like you have another `julia` on your `PATH`, not the version from Juliaup. Could that be? Can you run `get-command julia` and see what that returns?

**Comment by tbeason** [comment]
Hmm yes good catch. It points to chocolatey. I'm not sure when, but I must have used chocolatey in the past, and I think I recently did an "update all" there, which seems to have taken over my Julia installation (bc I definitely have been using juliaup for a while now). I did `choco uninstall julia` and removed/added `beta` in `juliaup` but I still get this:
```
Cannot find file at 'c:\users\beasont\appdata\local\programs\julia-1.8.5\bin\julia.exe' (c:\users\beasont\appdata\local\programs\julia-1.8.5\bin\julia.exe). This usually indicates a missing or moved file.
```

**Comment by tbeason** [comment]
I figured it out. `choco uninstall julia` didn't quite remove every trace. Some manual tracking down and a few file deletions later (plus trying lots of stuff that didn't work!), and now I'm running smoothly again. Sorry for the noise, but thanks for the help!
