### ISSUE TITLE
[Feature request] Include executable file for Windows to make juliaup easier to install.

### ISSUE THREAD

**Issue by hungpham3112** [JuliaLang/juliaup#597]
Hi. I tried to use juliaup on Pop OS and found juliaup really useful. Today I switch to Windows to install juliaup on my computer. 
I'm not into the winget way to install julia and juliaup in msstore so I wonder if exist the .exe file. 
Currently, I'm using julia 1.8.5 with scoop as my main package manager.

**Comment by davidanthoff** [comment]
Dup of https://github.com/JuliaLang/juliaup/issues/343.
