### ISSUE TITLE
[bug] juliaup status suggestion differs from what being actually updated

### ISSUE THREAD

**Issue by thoth291** [JuliaLang/juliaup#600]
I installed julia some time ago using juliaup on my PC.
When I did `juliaup list` I've got these versions available.
```
juliaup.exe list
 Channel           Version
--------------------------------------------------
...
 1.8.0~x64         1.8.0+0.x64.w64.mingw32
 1.8.0~x86         1.8.0+0.x86.w64.mingw32
 1.8.1             1.8.1+0.x64.w64.mingw32
 1.8.1~x64         1.8.1+0.x64.w64.mingw32
 1.8.1~x86         1.8.1+0.x86.w64.mingw32
 1.8.2             1.8.2+0.x64.w64.mingw32
 1.8.2~x64         1.8.2+0.x64.w64.mingw32
 1.8.2~x86         1.8.2+0.x86.w64.mingw32
 1.8.3             1.8.3+0.x64.w64.mingw32
 1.8.3~x64         1.8.3+0.x64.w64.mingw32
 1.8.3~x86         1.8.3+0.x86.w64.mingw32
 1.8.4             1.8.4+0.x64.w64.mingw32
 1.8.4~x64         1.8.4+0.x64.w64.mingw32
 1.8.4~x86         1.8.4+0.x86.w64.mingw32
 1.8~x64           1.8.4+0.x64.w64.mingw32
 1.8~x86           1.8.4+0.x86.w64.mingw32
 1.9               1.9.0-beta2+0.x64.w64.mingw32
...
```
When I checked for what version do I have - I've got:
```
juliaup.exe status
 Default  Channel  Version      Update
----------------------------------------------------------------------------
       *  release  1.8.3+0.x64  Update to 1.8.4+0.x64.w64.mingw32 available
```

Which clearly advised that I can update to 1.8.4 as my next version.
But when I executed `juliaup update` - I've got this:
```
juliaup.exe update
Installing Julia 1.8.5+0.x64.w64.mingw32
```

**My concerns:**
- I didn't see 1.8.5 in the list of available versions - but I see it now, after update
- The update string was misleading - since it mentioned 1.8.4 - but installed a different version.
- The update should start only after additional prompt to confirm that user indeed wants to install that exact version - installation interrupting is the least thing one wants to do

Possible reasons:
- Given that the release of 1.8.5 happened in January (I think) - it's unlikely that release registry for juliaup was updated only now
- Most likely, the reason is in the fact that `juliaup list` and `juliaup status` didn't refresh their local registry and provided me with outdated information.
- However - I did saw 1.8.4 - so that might be speculation on my part.

Hope this will be resolved soon.

**Comment by davidanthoff** [comment]
How we handle this has changed quite a bit recently, so I'm going to close this for now because I think this should be fixed. If you see this again, please do reopen this issue, though.

**Comment by thoth291** [comment]
@davidanthoff - I just did `juliaup update` and it, without any additional prompt - simply installed julia 1.9 for me.
**This is not good and additional prompt is needed.**
Also - I would like to confirm that I haven't noticed any issues with misleading suggestions vs actual installation since I updated to the last time.

**Comment by davidanthoff** [comment]
Why should we prompt again? If you instruct Juliaup to update things, it will do that. I don't see the need for more confirmations.

Note also that if you just want to see whether an update is available, you can just do `juliaup status`. And finally, if you want to not be updated so easily, then the `release` channel is not the right choice for you. You might want to install say the 1.8 channel with `juliaup add 1.8`, make that your default with `juliaup default 1.8` and then you will be shielded from minor versions updates.
