### ISSUE TITLE
Consider an alternative http package on Mac/Linux

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#604]
We've had numerous problem reports with ureq, and maybe we should investigate alternatives. Here are some options:

- https://github.com/seanmonstar/reqwest

- https://github.com/hyperium/hyper

**Comment by uncomfyhalomacro** [comment]
Could I try to test both of these next week?

**Comment by davidanthoff** [comment]
I just took a (very brief) look at both, and my sense is that hyper is all about async, it was not even clear to me whether one could use it without tokio? If that is so, we should probably look into reqwest first, I would prefer to not bundle tokio or go this async framework route for now, I think in a simple client like scenario we don't really need that complexity.

**Comment by tecosaur** [comment]
Reqwest is built on hyper, so you get the benefit of it being built on "the big battle tested" library, but you can use it synchronously https://github.com/seanmonstar/reqwest#blocking-client.

It might also be of interest that rustls can be used instead of the system's TLS library, which might be nice for portability.

**Comment by uncomfyhalomacro** [comment]
> Reqwest is built on hyper, so you get the benefit of it being built on "the big battle tested" library, but you can use it synchronously https://github.com/seanmonstar/reqwest#blocking-client.
> 
> It might also be of interest that rustls can be used instead of the system's TLS library, which might be nice for portability.

Got off from the holidays. I will check this out. thanks!

**Comment by uncomfyhalomacro** [comment]
@tecosaur regarding your suggestion with rustls vs native-tls, I will be waiting for @davidanthoff or others opinion about them.

For now, I will be just using native-tls since
> in environments with stricter requirements you want native tls

from someone I know.

Let me know if there are advantages/disadvantages between those crates :D

**Comment by uncomfyhalomacro** [comment]
I will open a PR soon. Also I will rename the functions into generic names. ureq to reqwest is really a minor change. took me a while since I haven't touched rust for a year or two

**Comment by davidanthoff** [comment]
> Also I will rename the functions into generic names.

In general, the less change the PR introduces, the faster we can merge it :) Ideally try to make the minimal PR, and if we should rename stuff we can do that in a separate PR.

> It might also be of interest that rustls can be used instead of the system's TLS library, which might be nice for portability.

We iterated a lot on that and ended up where we are today essentially thinking that this is the best solution. Problem is, right now I can't recall where we landed ;) But I think it was essentially something where we wanted to rely on the system certificate list because otherwise things don't work for folks that have custom proxy situations.

> I will open a PR soon.

Fantastic!!

**Comment by uncomfyhalomacro** [comment]
rustls can finally use system certs but idk much about it and if it is reliable. I just sticked to native-tls since this is what juliaup ended up with.

**Comment by uncomfyhalomacro** [comment]
@davidanthoff hello. i made a pr #613 but it seems i cannot build it correctly to musl (see github actions) because of openssl. not sure why though. maybe because the system's environment is glibc while we are building a binary for musl

**Comment by davidanthoff** [comment]
This is now merged on `main`.
