### ISSUE TITLE
Suspending Julia via Ctrl-Z requires two presses

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/juliaup#607]
The following happens for me with Julia 1.6.7, 1.8.5 and 1.9.0rc1 on both macOS 12.6.4 and a Ubuntu 20.04.

On Unix like systems (including macOS and Linux) one can usually suspend programs with a REPL using Ctrl-Z and then later resume them (e.g. by entering `fg` in bash).

This kinda works for Julia, but one has to press ctrl-Z twice: after the first press, Julia is in a weird limbo state: it echos whatever I type, even overdrawing its own REPL prompt, but is otherwise unresponsive. Ctrl-C is also ignored. Pressing ctrl-Z a second time then fully suspends it and I am back in my shell.

Also, if I press Ctrl-Z Ctrl-C Ctrl-Z and then resume it (via `fg`), it crashes.

**Comment by fingolfin** [comment]
A trivial way to fix this would be if the launcher just replaced itself with Julia (i.e., no `fork`, just `exec`), instead of launching Julia as a child process. It seems to do the latter in order to check for updates? But I'd gladly trade that for having this issue resolved; I really prefer to run `juliaup update` manually anyway

**Comment by StefanKarpinski** [comment]
Yes, or fork the update process (orphan it) and then exec the main Julia process.
