### ISSUE TITLE
Host crate on Cargo as well

### ISSUE THREAD

**Issue by garrison** [JuliaLang/juliaup#618]
Following https://github.com/JuliaLang/juliaup/issues/615#issuecomment-1513926408, it would be great to be able to install using `cargo install juliaup`.  The rationale is that many systems (Linux distributions, in particular) have working Rust installations, and this would provide a convenient, hash-verified way to install on those platforms.

**Comment by davidanthoff** [comment]
If someone can figure out how we can have `julialauncher` automatically appear as `julia` when installed via cargo, then I'm all for it.

**Comment by MilesCranmer** [comment]
> If someone can figure out how we can have `julialauncher` automatically appear as `julia` when installed via cargo, then I'm all for it.

If I understand correctly, could use the `[[bin]]` key in the TOML file? i.e.,

```toml
[[bin]]
name = "julia"
path = "src/main.rs"
```

**Comment by uncomfyhalomacro** [comment]
i was going to suggest that. yes you can do that. If he is busy, i'm opening a pr. :)

**Comment by davidanthoff** [comment]
The thing is we need it to be `julialauncher` for all situations that are not a `cargo install`, and `julia` for the `cargo install` scenario.

**Comment by MilesCranmer** [comment]
(You mean juliaup, not julia, right?)

couldn’t you make the bin name “julialauncher” in the TOML specification, and the package name juliaup (which is currently is)?

**Comment by MilesCranmer** [comment]
Thanks for explaining. So the above code would work for this right? You would just specify the binary name as “julia” in the Cargo TOML. And `cargo install` would still be `juliaup`

**Comment by davidanthoff** [comment]
Yes, but I believe it would mess up the compile stage for all the other deployments.

**Comment by MilesCranmer** [comment]
This works will for me actually! Just tried it with a local install in a docker.
```toml
[[bin]]
name = "julia"
path = "src/bin/julialauncher.rs"
```

**Comment by MilesCranmer** [comment]
Made a PR in #639

**Comment by davidanthoff** [comment]
> It will result in both a `julia` and a `julialauncher` in the cargo bin folder.

Oh, I didn't realize that is what would happen. Excellent, that essentially solves it!
