### ISSUE TITLE
Juliainstaller Crash Report

### ISSUE THREAD

**Issue by junebug1717** [JuliaLang/juliaup#630]
When I attempt to drop the crash report github tells me that it doesn't like the TOML file type.

[report-9d63f0a9-d544-4207-9f10-e329c2661bb6.toml.gz](https://github.com/JuliaLang/juliaup/files/11421680/report-9d63f0a9-d544-4207-9f10-e329c2661bb6.toml.gz)

**Comment by jjvliu** [comment]
Contents:

```
name = 'Juliainstaller'
operating_system = 'unix:OSX'
crate_version = '1.8.16'
explanation = '''
Panic occurred in file 'src/operations.rs' at line 749
'''
cause = '''
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/ma20958/.bash_profile.

Caused by:
    Permission denied (os error 13)'''
method = 'Panic'
backtrace = '''

   0: 0x1029c8a88 - juliaup::command_config_modifypath::run_command_config_modifypath::h0f87529dd7cef58e
   1: 0x10290f0a8 - juliainstaller::main::h6342f9beb07f076b
   2: 0x1028f80d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hda91fd22e5148544
   3: 0x102914b7c - _main'''`
```

Looks like the same issue as #624.

**Comment by davidanthoff** [comment]
I believe that when we fix https://github.com/JuliaLang/juliaup/issues/624, then this error here should also be sorted out. So I'm going to close this issue for now, I think technically it is a duplicate.
