### ISSUE TITLE
can't use juliaup override

### ISSUE THREAD

**Issue by floswald** [JuliaLang/juliaup#644]
for some reason I cannot use the `override` command. I'm using fish and in general juliaup works flawlessly.

```
floswald@PTL11077 ~/.j/d/LandUse (master)> juliaup --version             
Juliaup 1.8.16

floswald@PTL11077 ~/.j/d/LandUse (master)> juliaup override              
error: The subcommand 'override' wasn't recognized

Usage: juliaup <COMMAND>

For more information try '--help'
floswald@PTL11077 ~/.j/d/LandUse (master) [2]> juliaup override --help   
error: The subcommand 'override' wasn't recognized

Usage: juliaup <COMMAND>

For more information try '--help'
floswald@PTL11077 ~/.j/d/LandUse (master) [2]> juliaup override set 1.8.5
error: The subcommand 'override' wasn't recognized

Usage: juliaup <COMMAND>

For more information try '--help'
```

**Comment by davidanthoff** [comment]
That feature was (until a moment ago) only on the dev channel, which essentially has only me on it ;) I just pushed that build to the releasepreview channel. If you want to try it, take a look at https://github.com/JuliaLang/juliaup/wiki/Trying-a-release-candidate.

We probably just need to move the docs to something at some point where we can keep new features out of the "stable" docs until they really ship...
