### ISSUE TITLE
Juliaup launcher Crash Report

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/juliaup#660]
I am using the newest Juliaup and the newest Julia (1.9.1) via juliaup (`juliaup add 1.9`). I can't run `versioninfo()` because Julia won't start.

Here is the crash report:
```
name = 'Juliaup launcher'
operating_system = 'unix:Unknown'
crate_version = '1.8.16'
explanation = '''
Panic occurred in file 'src/config_file.rs' at line 120
'''
cause = 'called `Result::unwrap()` on an `Err` value: Os { code: 524, kind: Uncategorized, message: "No error information" }'
method = 'Panic'
backtrace = '''

   0: 0x7fffed63ea15 - julialauncher::main::h7c3cfe36d9073d96
   1: 0x7fffed6343c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hafff6f50adcb8cae
   2: 0x7fffed64650e - main'''
```

I am running on Frontier, and HPC system at OLCF <https://www.olcf.ornl.gov/frontier/>. I installed Juliaup and Julia on a login node, and I am receiving this crash report when running on a compute node.

**Comment by davidanthoff** [comment]
I believe a dup of https://github.com/JuliaLang/juliaup/issues/252.
