### ISSUE TITLE
Please add specific release command to `juliaup` help text

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/juliaup#686]
Please add something like this to the `juliaup` help text:

`To launch a specific Julia version, say in channel release, run julia +release.`

Otherwise there's no way to discover this without coming to GitHub.

**Comment by fingolfin** [comment]
Note that the help text *does* include this information, but perhaps too hidden?
```
$ juliaup
The Julia Version Manager

Usage: juliaup <COMMAND>

Commands:
  default   Set the default Julia version
  add       Add a specific Julia version or channel to your system. Access via `julia +{channel}` e.g. `julia +1.6`
[...]
```


I made PR #779 to show a similar message at the end of the full help text, perhaps that makes it easier to see / harder to miss?

**Comment by BioTurboNick** [comment]
Yeah, I would have overlooked it because I'm not trying to add, I'm trying to run.
