### ISSUE TITLE
JULIA_DEPOT_PATH env var seems to be ignored when I use `curl ... | sh`

### ISSUE THREAD

**Issue by JBlaschke** [JuliaLang/juliaup#693]
This is an odd one that I can't quite figure out. When I use:

```bash
JULIA_DEPOT_PATH=~/.julia2 curl -fsSL https://install.julialang.org | sh -s -- --yes --add-to-path=0 --path ~/.juliaup2
```

It still installs Julia to `~/.julia` (and not `~/.julia2` like I asked it to). The Juliainstaller doesn't seem to be broken per se though. When I build with `cargo build --features=selfupdate,binjuliainstaller` and then use my local `juliainstaller`:

```bash
JULIA_DEPOT_PATH=~/.julia2 ./juliainstaller --yes --add-to-path=0 --path ~/.juliaup2
```

Then it does install to `~/.julia2`.

Right now I have no clue what's causing this. And I can live with using my local build. But thought someone ought to know.

**Comment by uncomfyhalomacro** [comment]
@JBlaschke i feel like the pre-built binary used for the script is missing some features

**Comment by DilumAluthge** [comment]
@JBlaschke Can you try the following?

```bash
export JULIA_DEPOT_PATH=~/.julia2

curl -fsSL https://install.julialang.org | sh -s -- --yes --add-to-path=0 --path ~/.juliaup2
```

**Comment by JBlaschke** [comment]
Huh! This took me AAAAAGES to figure out (and feel kinda stupid): The example above just wouldn't work and I was digging around the bash/sh docs. Then (after revisiting this issues a fews months later) I noticed that the example above creates a folder called `~` -- which my terminal (fish+exa) promptly hides.

Anyway, the following works:
```
export JULIA_DEPOT_PATH=$HOME/tmp/julia
curl -fsSL https://install.julialang.org | sh -s -- --add-to-path=0 --yes --path ~/tmp/juliaup
``` 
(I.e. my shell doesn't expand `~` when it's used in a variable).

Anyway this works. I can clean my production system up now.

**Comment by uncomfyhalomacro** [comment]
@JBlaschke we should probably add fish script here and an updated instruction.
