### ISSUE TITLE
New install: julia hangs for few seconts and does nothing

### ISSUE THREAD

**Issue by pjssilva** [JuliaLang/juliaup#71]
Hello I tried to install juliaup from the Windows Store. After installation if I call Julia from the start menu the REPL windows opens, fully black, hangs for a few seconds and closes. If I try to call julia in the shell (both PowerShell and Command Prompt) the call hangs for some seconds and returns to the prompt without opening thee REPL.

I can confirm that `juliaup` was installed, as it seems to work. For example:
```
PS C:\Users\XXXXXXX> juliaup status
Installed Julia channels (default marked with *):
  * release
 ```
I also have the `~/.julia` directory and I even can find the julia executable in there at `~/.julia\juliaup\julia-1.6.1+0~x64\bin`. I can even make it work by moving to that dir and typing ` ./julia` at PowerShell.

I have also checked whether something that looks like a symlink to the julia executable appears in the `~\AppData\Local\Microsoft\WindowsApps` and it looks like it is there (I am no expert in Windows):
```
PS C:\Users\XXXXXXXXXX\AppData\Local\Microsoft\WindowsApps> ls


    Diretório: C:\Users\XXXXXXXXXXX\AppData\Local\Microsoft\WindowsApps


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        14/07/2021     20:36                Backup
d-----        14/07/2021     20:39                JuliaComputingInc.Julia_b0ra4bp6jsp6c
d-----        27/11/2020     19:18                Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
d-----        14/07/2021     11:50                Microsoft.MicrosoftEdge_8wekyb3d8bbwe
d-----        14/07/2021     20:19                Microsoft.SkypeApp_kzf8qxf38zg5c
d-----        14/07/2021     20:18                Microsoft.XboxGamingOverlay_8wekyb3d8bbwe
-a---l        14/07/2021     20:18              0 GameBarElevatedFT_Alias.exe
-a---l        14/07/2021     20:39              0 julia.exe
-a---l        14/07/2021     20:39              0 juliaup.exe
-a---l        20/04/2021     18:28              0 MicrosoftEdge.exe
-a---l        27/11/2020     19:18              0 python.exe
-a---l        27/11/2020     19:18              0 python3.exe
-a---l        14/07/2021     20:19              0 Skype.exe
```
I am not sure what I can try next.

**Comment by davidanthoff** [comment]
Is there a file `~.\.julia\juliaup\juliaup.json`? If it is, could you post the content of that here?

One other idea: are there any spaces or special Unicode characters in your profile directory name, i.e. the part that you `XXX`ed out? Staring at the C++ code, I am actually starting to think that I might have an error in how I handle (or rather don't) Unicode characters in paths...

Oh, and just to confirm: you never called `juliaup add` or `juliaup update` in any form, right?

Thanks so much for the detailed error report!

**Comment by pjssilva** [comment]
The juliaup.json is there. Its contents are:

```json
{
    "Default": "release",
    "InstalledChannels": {
        "release": {
            "Version": "1.6.1+0~x64"
        }
    },
    "InstalledVersions": {
        "1.6.1+0~x64": {
            "Path": ".\\julia-1.6.1+0~x64"
        }
    }
}
```

My user name is "Paulo J. S. Silva" with the spaces but no accents or other diacritics. 

I have never called `juliaup add` or `juliaup update`.  If want me to try something else, please just let me know.

**Comment by davidanthoff** [comment]
The file looks good, that can't be it... I'm building a version now that outputs a bit more diagnostics, maybe that will help. One thing that would be great is if I could put you on a different version in the store (or flight, as it is called in Windows Store terminology), that way I could push new builds out much quicker to you to try to get to the bottom of this. To do that I would need to know your Microsoft Account name. If that would be ok, could you maybe send that either to my email address (on my GitHub profile) or via Slack? Once we have resolve this I'd put you back on the normal version in the store. There is nothing else you would need to do, i.e. can configure that you get special builds on my end as long as I know your Microsoft Account.

**Comment by aramirezreyes** [comment]
I'm sorry if this is not the problem but I wonder if this is related. But did you have a previous Julia install with something in `~/.julia/startup.jl`? I have had julia sessions die immediately for some thing that are in that file (something related to revise perhaps).

**Comment by davidanthoff** [comment]
@pjssilva I've actually pushed the build with more diagnostic output to everyone. It will take a few hours for that to make it through the Windows Store pipeline, but then it should auto-install for you. Once you are on version 1.0.56.0 (you can see that in the Store, or via `juliaup -v`), can you then try to run `julia` again from PowerShell? Hopefully it should now show some diagnostic output.

@aramirezreyes ah, that is a good idea! But I'm actually fairly positive that in this case there is a real bug in my stuff: I can see that there is one machine in Brazil that properly crashes, the Windows Store shows me that much information (but nothing else). So my best guess is that that is actually @pjssilva :)

**Comment by pjssilva** [comment]
@aramirezreyes I don't remember using Julia in this machine at all. I actually don't user Windows, basically never. But I am going to give to courses at the University that involve Julia and I had decided to try `juliaup` to see if it was an easy way for the students to install Julia.

@davidanthoff I have sent you my Microsoft user by email. I have also tried the new version on power shell. It outputs
```
PS C:\Users\Paulo J. S. Silva\.julia\juliaup> julia
The latest version of Julia in the `release` channel is 1.6.2+0~x64. You currently have 1.6.1+0~x64 installed. Run:

  juliaup update

to install Julia 1.6.2+0~x64 and update the `release` channel to that version.
runtime_error: %1 nÒo Ú um aplicativo Win32 vßlido.
```
The first part is just warning me that Julia 1.6.2 was just released. The actual error is on the last line. The string is trying to say in Portuguese "não é um aplicativo Win32 válido". As you can see the accented characters are garbled. Probably a bad encoding is being used. In English the same string should probably be "It is not a valid Win32 application".

**Comment by davidanthoff** [comment]
Ah, this is all super helpful!

I looked at the code again, and I'm actually simply not handling spaces in paths properly, so pretty sure that explains the error you are seeing. I'm pushing a new build right now that should fix that. And I also tried to fix the encoding for error messages, although I am a little less sure whether I got that one right.

And thanks for your email, I'm going to push this new build out to just you, and maybe you could let me know if that fixes things for you? If it does, I'm going to release it broadly. The version of the new build is 1.0.57.0. It is going through the store submission right now, but that shouldn't take too long (they run fewer tests on it if it is pushed to a private target group like you).

**Comment by pjssilva** [comment]
@davidanthoff I am still at 1.56.0. Do I need to do anything on my end. Like uninstall juliaup and install again?

**Comment by davidanthoff** [comment]
@pjssilva, in theory you should just automatically get the update, I think, as long as the email address you sent me is the one you use to logon to Windows itself. You could maybe check in the Windows Store app for updates?

**Comment by pjssilva** [comment]
I had to logout and login again to make it install thee new version. `juliap -v` now gives v1.0.57 (no .0 at the end). Most important: it works! Great! Thanks  @davidanthoff!

**Comment by davidanthoff** [comment]
Fantastic, thanks for providing all that detailed info, that was a pretty important bug to fix :) I'll push this build out to everyone now and then I'll move you back to the normal released versions.
