### ISSUE TITLE
Calling `juliaup update` from within julia doesn't work

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/juliaup#72]
```
shell> juliaup update
Installing Julia 1.6.2+0 (x64).
New version successfully installed.
ERROR: UndefVarError: path_to_delete not defined
Stacktrace:
 [1] garbage_collect_versions(config_data::Dict{String, Any})
   @ Juliaup D:\a\juliaup\juliaup\Juliaup\src\Juliaup.jl:211
 [2] real_main()
   @ Juliaup D:\a\juliaup\juliaup\Juliaup\src\Juliaup.jl:343
 [3] julia_main()
   @ Juliaup D:\a\juliaup\juliaup\Juliaup\src\Juliaup.jl:11
 [4] julia_main()
   @ Main .\none:36

caused by: IOError: unlink("C:\\Users\\nicho\\.julia\\juliaup\\.\\julia-1.6.1+0~x64\\bin\\LLVM.dll"): permission denied (EACCES)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:97 [inlined]
 [2] unlink(p::String)
   @ Base.Filesystem .\file.jl:934
 [3] rm(path::String; force::Bool, recursive::Bool)
   @ Base.Filesystem .\file.jl:272
 [4] rm(path::String; force::Bool, recursive::Bool) (repeats 2 times)
   @ Base.Filesystem .\file.jl:282
 [5] garbage_collect_versions(config_data::Dict{String, Any})
   @ Juliaup D:\a\juliaup\juliaup\Juliaup\src\Juliaup.jl:207
 [6] real_main()
   @ Juliaup D:\a\juliaup\juliaup\Juliaup\src\Juliaup.jl:343
 [7] julia_main()
   @ Juliaup D:\a\juliaup\juliaup\Juliaup\src\Juliaup.jl:11
 [8] julia_main()
   @ Main .\none:36

shell>
```

Says successfully installed, but running Julia again it still runs 1.6.1:
```
The latest version of Julia in the `release` channel is 1.6.2+0~x64. You currently have 1.6.1+0~x64 installed. Run:

  juliaup update

to install Julia 1.6.2+0~x64 and update the `release` channel to that version.
```

I imagine the issue might be that it's trying to delete the running copy of Julia, which is fair. But it might be more graceful to detect that copy of Julia is running, change the default to point to 1.6.2, and instruct the user to run `juliaup remove 1.6.1` to remove the previous version. That notice could either appear there (and the user would need to remember), or as a pre-launch notice when running the new version, that the old version needs to be removed.

That said, it says install was successful, but on the next run, it doesn't show the new version as being installed with `juliaup status`.

**Comment by davidanthoff** [comment]
Ah, that is a pretty silly bug :) I actually tried to handle this exact scenario gracefully [here](https://github.com/JuliaLang/juliaup/blob/3bb47b48c6fecbac993c01564b666cf18673250e/Juliaup/src/Juliaup.jl#L211) but then incorrectly put something into the `try` block that should have been outside. The next PR should fix this problem. Thanks for reporting!
