### ISSUE TITLE
Hourly mail from julia installer on osx?

### ISSUE THREAD

**Issue by tyoc213** [JuliaLang/juliaup#723]
```
? 1
Message 1:
From tyoc213@laptop.local  Fri Aug 25 20:00:01 2023
X-Original-To: tyoc213
Delivered-To: tyoc213@laptop.local
From: tyoc213@laptop.local (Cron Daemon)
To: tyoc213@laptop.local
Subject: Cron <tyoc213@laptop.local> /var/folders/g8/d32jhp1d5fqc35nc556w3ztm0000gn/T/tmp.yh9esVEj/juliainstaller 4c79c12db1d34bbbab1f6c6f838f423f
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=tyoc213>
X-Cron-Env: <USER=tyoc213>
Date: Fri, 25 Aug 2023 20:00:00 -0600 (CST)

/bin/sh: /var/folders/g8/d32jhp1d5fqc35nc556w3ztm0000gn/T/tmp.yh9esVEj/juliainstaller: No such file or directory
```

But 

```
 less /etc/crontab
/etc/crontab: No such file or directory
```

And

```
 crontab -l
*/300 * * * * /var/folders/g8/d32jhp1d5fqc35nc556w3ztm0000gn/T/tmp.yh9esVEj/juliainstaller 4c79c12db1d34bbbab1f6c6f838f423f
```

Which doesn't exist

**Comment by davidanthoff** [comment]
@tyoc213, can you provide a bit more info? What platform? How did you install? Did you choose the option for background updates during setup?

**Comment by DilumAluthge** [comment]
> Also, there is really nothing in Juliaup that would send an email, as far as I can tell, so there must be something else going on with your system? Have you configured it in some way to send emails?

Does JuliaUp create a cron job? I'm guessing that the system is sending mail because that cron job is failing.

**Comment by StefanKarpinski** [comment]
There is some reference to creating cron jobs in the code: https://github.com/search?q=repo%3AJuliaLang%2Fjuliaup%20cron&type=code.

**Comment by davidanthoff** [comment]
Yes, there is an option in the setup to have Juliaup periodically check for new versions via a cronjob. Not sure what to do about this right now, hard to diagnose without more info... I'll close for now until we have a bug report with more details.
