### ISSUE TITLE
Inconsistent architectures for 1.7.2 and 1.7.3 on macOS

### ISSUE THREAD

**Issue by 3f6a** [JuliaLang/juliaup#725]
I am on macOS with an M-series processor. `juliaup add 1.7.3`  installs a x64 version, while `juliaup add 1.7.2` installs an arm version. This seems inconsistent.

```bash
$ juliaup add 1.7.3
Installing Julia 1.7.3+0.x64.apple.darwin14
...

$ juliaup add 1.7.2
Installing Julia 1.7.2+0.aarch64.apple.darwin14
...
```

Output of versioninfo(), run from latest stable version of Julia:

```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

**Comment by StefanKarpinski** [comment]
What's the output of `file $(which juliaup)`?

**Comment by StefanKarpinski** [comment]
Ok, I'm out of my depth here. I wonder if the aarch64 version of 1.7.3 is missing for some reason?

**Comment by DilumAluthge** [comment]
It's missing from https://julialang.org/downloads/oldreleases/, at least

**Comment by davidanthoff** [comment]
So that presumably also means it is not in `versions.json`? If so, that would explain it. We used to have all this special logic here in Juliaup to decide which versions exist, but since I moved things over to just mirror `versions.json`, all of that special casing is gone and we just reflect the state of `versions.json`.

**Comment by davidanthoff** [comment]
Ok, I checked, and there just doesn't exist a 1.7.3 aarch64 build in versions.json on Mac. I think this is an issue for https://github.com/JuliaLang/VersionsJSONUtil.jl, i.e. if that build exists somewhere and were listed in that version database, it would also show up in Juliaup automatically.
