### ISSUE TITLE
1.9.3 and 1.10-beta3 are missing from list

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaLang/juliaup#735]
I probably missed something, but it seems like the two newest versions are missing:

![Screenshot_20231004_215840](https://github.com/JuliaLang/juliaup/assets/6344099/a623ff64-7152-44ce-ad97-daf9a28562f3)

https://discourse.julialang.org/t/julia-v1-10-0-beta3-is-now-available/104551

Juliaup 1.11.22
Garuda Arch Linux

**Comment by davidanthoff** [comment]
Is this still a problem?

**Comment by davidanthoff** [comment]
I can't replicate this, so closing for now.

**Comment by ShalokShalom** [comment]
I forgot to update on this. They got added a couple of days after I opened this report. So its fine now. :)

Thanks a lot
