### ISSUE TITLE
`juliaup self uninstall` does not exist? `error: unrecognized subcommand 'uninstall'`

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/juliaup#745]
I'm trying to uninstall juliaup following the command on README.md:

```shell
juliaup self uninstall
```

But it does not work:

<img width="275" alt="image" src="https://github.com/JuliaLang/juliaup/assets/25192197/4a961e27-16cc-4e0a-aab5-09aff362d112">

<img width="456" alt="image" src="https://github.com/JuliaLang/juliaup/assets/25192197/818010c8-e16a-46bc-84f8-a96365132cb4">

PS. I installed juliaup from homebrew on macOS.

**Comment by davidanthoff** [comment]
When you install Juliaup using a third party package manager, you'll also have to uninstall it using that, i.e. some brew specific command. `juliaup self uninstall` only works if you installed it via the shell script in the README.

**Comment by StefanKarpinski** [comment]
Should there perhaps be a dummy `uninstall` command that just tells you that? Or at least a change to the README?

**Comment by davidanthoff** [comment]
https://github.com/JuliaLang/juliaup/issues/752
