### ISSUE TITLE
Provide better UI for `self uninstall` on platforms that don't actually support it

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#752]
Right now `juliaup self uninstall` is an error as "unknown command" on platforms where Juliaup is installed via some third party method (brew, cargo etc). Instead of just pretending that the command doesn't exist, we could either output a more useful error message, or maybe on some platforms even initiate the uninstall (similar to Windows, where `juliaup self update` triggers a Windows Store update for Juliaup).

**Comment by uncomfyhalomacro** [comment]
\cc @davidanthoff . not sure if the PR linked / mentioning this issue solves this.
