### ISSUE TITLE
"ERROR: Invalid Juliaup channel `1.0` at command line."

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/juliaup#766]
This channel isn't really "invalid", I just hadn't installed it yet. I think a simple fix would be "Invalid or uninstalled Julia channel". A fancier fix would be to lookup if it is just not yet installed, and if running interactively, prompt to do so, given we are on an error path anyway and can afford the lookup time.

**Comment by uncomfyhalomacro** [comment]
what command did you run? sorry need more context 👀

**Comment by ericphanson** [comment]
It's just the default message when you try to use a channel you don't have installed. E.g. if you don't have the 1.0 channel installed, then:
```sh
julia +1.0
ERROR: Invalid Juliaup channel `1.0` at command line.
```

**Comment by uncomfyhalomacro** [comment]
I wonder if it should just install the channel. it's weird that running `julialauncher` with no arguments will just download julia latest stable if it does not exist. that command should also do that too with the specific channel/version

**Comment by uncomfyhalomacro** [comment]
https://github.com/JuliaLang/juliaup/blob/4e8c47a73e090a0170de829d7e68dd9fda7eb576/src/bin/julialauncher.rs#L155-L206

This line and similar functions can be changed entirely.
1. Check if the channel is one of the valid channels
2. If it's a valid channel, attempt to check if it's already downloaded.
3. If it's not downloaded yet, download it and then run it

**Comment by davidanthoff** [comment]
In general I don't think we should just automatically download stuff. The bootstrap for the default version is a bit of an exception, but only on certain platforms, for example the Windows Store version ships the default channel as part of the setup itself and then doesn't need to download that.

I _do_ think we should be much more helpful in interactive mode, i.e. shows prompts like "Do you want to install bla bla?" etc. The main obstacle right now is that we can't distinguish at the moment in `julialauncher` whether Julia is running in interactive mode or not. For that to work we need to parse the command line args properly...

**Comment by ericphanson** [comment]
FWIW `rustup`'s approach here is just a clearer error, which I think would be an improvement over the status quo:
```sh
❯ rustup run nightly cargo build
error: toolchain 'nightly-aarch64-apple-darwin' is not installed
```
FWIW it doesn't seem to do anything special for the "invalid" case:
```sh
❯ rustup run blah cargo build
error: toolchain 'blah' is not installed
```
It just always says "not installed". Which IMO is better than "invalid", because it hints at what you should do to fix it (install it!).

**Comment by davidanthoff** [comment]
Yes, I should say, making that error message is a very low hanging fruit that we should definitely do!

**Comment by uncomfyhalomacro** [comment]
> Yes, I should say, making that error message is a very low hanging fruit that we should definitely do!

already made a pr #767. hoping for your kind review :D
