### ISSUE TITLE
Juliainstaller Crash Report

### ISSUE THREAD

**Issue by lg-montoya** [JuliaLang/juliaup#777]
[My Mac OS versions uses zsh as default shell. Installer seems to crash when .bashrc is not found? I can confirm I already have a .zshrc. I do not have .bashrc. I am using M3 max apple silicon]

"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.2.1 [64-bit]"
"crate_version" = "1.12.5"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 794
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/user_foo/.bashrc.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x10523ddc0 - core::result::unwrap_failed::h16d42dbc22454d03
   1: 0x1050c1cf8 - juliaup::command_config_modifypath::run_command_config_modifypath::h3a52147342705b23
   2: 0x104fbfc68 - juliainstaller::main::hcefe810cede6f201
   3: 0x104fa984c - std::sys_common::backtrace::__rust_begin_short_backtrace::hf33c18d3a0004e24
   4: 0x104fc5294 - _main"""

**Comment by lg-montoya** [comment]
Forgot to add that I am on apple silicon MBP M3 max

**Comment by lg-montoya** [comment]
Hello

Yes, you are right. There was an offending .bashrc file that I was not aware of. My bad.

Luis

On 4 Jan 2024, at 05:16, Max Horn ***@***.***> wrote:


That's weird, because only tries to touch .bashrc if it exists (same for .zshrc and others). The error you print would fit with .bashrc existing, but not being accessible due to file permissions.

Could you perhaps double check that ~/.bashrc really doesn't exist?

**Comment by fingolfin** [comment]
Great, thanks for double checking.

Feel free to close this issue :-)
