### ISSUE TITLE
GH actions checks complain about "calls to `std::mem::drop` with a reference instead of an owned value does nothing"

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/juliaup#778]
Looking at any recent pull request, the "check-juliaup" action reports several warnings about
> calls to `std::mem::drop` with a reference instead of an owned value does nothing

as "Unchanged files with check annotations". See e.g. [here](https://github.com/JuliaLang/juliaup/pull/753/files) (that PR is *not* causing those warnings, they come from the `main` branch).

Unfortunately I don't really know Rust and so can't judge whether these are problematic, or what the correct fix (if any) is, but it would be nice to not have this noise show up in all PRs.

**Comment by uncomfyhalomacro** [comment]
Running `cargo clippy`, I see a lot of clippy errors and warnings screaming at me. 
![image](https://github.com/JuliaLang/juliaup/assets/66054069/6f340a2a-31c6-4cac-9778-d9a66073b05a)
