### ISSUE TITLE
Error: Failed to update versions db

### ISSUE THREAD

**Issue by francisbarton** [JuliaLang/juliaup#797]
Hi

I've recently installed Julia 1.10 from the Windows Store using

```
winget install julia -s msstore
```

At the Git bash command line if I run Julia I get:

```
$ julia
Error: The Julia launcher failed to figure out which juliaup channel to use.
```

If I run juliaup status:

```
$ juliaup status
 Default  Channel  Version  Update 
-----------------------------------
```

i.e. there are no channels ready to use. If I try to add a channel:

```
$ juliaup add 1.10
Error: Failed to update versions db.

Caused by:
    0: Failed to download current version db version.
    1: Failed on http_client.GetStringAsync.get
    2: A redirect request will change a secure to a non-secure connection (0x80072F08) 
```

The same with:

```
$ juliaup self update
Error: Failed to update versions db.

Caused by:
    0: Failed to download current version db version.
    1: Failed on http_client.GetStringAsync.get
    2: A redirect request will change a secure to a non-secure connection (0x80072F08) 
```

```
$ juliaup list
```

gives me a long list of channel options. I just can't seem to add any of them.

Any ideas how to fix this please?

StackOverflow [says](https://stackoverflow.com/a/32998982):

```
The error (0x80072f08) means you are doing a HTTPS request that is responding with a redirection to a HTTP url.
```

I'm quite new to Julia so I don't know where to look for things like finding out where the juliaup update db server is located, and so on.

I was using Julia 1.9.3 just fine until now, but then I switched to the Windows Store pathway when I chose to move to 1.10.

```
$ juliaup -V
Juliaup 1.12.0
```

**Comment by davidanthoff** [comment]
Hm, not sure. The error message to me seems to indicate that something (presumably on your corporate network) is redirecting our request to a (secure) `https` location to an (unsecure) `http` location. I don't know what exactly is doing that, but it seems _very_ insecure to me and I think Juliaup right now correctly errors in such a situation... We are downloading software to a computer, and so I really don't want us to download from random unsecure locations, that seems like a huge security problem.

I think the main question is what is causing that in the first place...

**Comment by francisbarton** [comment]
Thanks again David, I appreciate your patience and the detail.

I assume that the server juliaup is trying to reach is https://julialang-s3.julialang.org/ (as per the README). I can access that site fine in my browser (with https) so I don't really understand why a command line tool would be blocked or redirected. I appreciate that it an issue at my end, however, not a problem with juliaup, even if I don't know how to fix it.

I think if I report it to my corporate IT department they will just say "well that domain isn't blocked".

**Comment by francisbarton** [comment]
My corporate IT helpdesk finally got to looking at this last week and it was indeed caused by a proxy issue. He cleared the proxy cache in the Windows registry and juliaup worked fine. Once the cache started filling up again, I could no longer use refresh juliaup data.

(This proxy issue is causing all sorts of issues for at my organisation, but that's another matter!)
