### ISSUE TITLE
[idea] maybe use `pin` instead of `setdefault`

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/juliaup#80]
When reading it, I wondered if we could streamline the names with Pkg itself. So `setdefault` just annoyed me in some sense. Given that `pin` is the command in pkg which locks a certain version to be used in the package, setting the default is actually pretty much the same.
As another alternative, which also doesn't follow the pkg naming, would instead follow the julia naming convention:
`default! 1.5` would set the default to 1.5 ^^

Just some thoughts that came to my mind when reading it ^^

**Comment by rapus95** [comment]
That indeed could be misleading. I'm fine with sticking to just `default`. It aligns perfectly with the argument-less execution that could show the default.
Ah, btw, couldn't check it so far, are the abbreviated commands supported aswell? I.e. st, rm

**Comment by davidanthoff** [comment]
> Ah, btw, couldn't check it so far, are the abbreviated commands supported aswell? I.e. st, rm

Yes!

**Comment by rapus95** [comment]
Then it's perfect! Sorry for interrupting your work :D

**Comment by davidanthoff** [comment]
No problem, thanks for the feedback :)
