### ISSUE TITLE
Should it be `jlup` instead of `juliaup`?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#81]
Or both? Although I'm not a fan of two options for the same thing. My own small preference is to stick with `juliaup`, but I did want to put the option out here :)

**Comment by heetbeet** [comment]
I like juliaup more than jlup, it's more explicit. On a similar note, it might be useful to add `julia --up` and `julia -u` as an alias for `juliaup` in the thin launcher. This would allow doing everything from a single entry point and would communicate a type of unity and officiality to the juliaup way of doing. Plus if the `julia --help` gets extended as well, then it can help newcomers with easily getting new versions installed. This might be a bit bikeshedding though.

I would say `julia -u` > `juliaup` > `jlup`

**Comment by heetbeet** [comment]
Plus another benefit is that you know if you access `juliaup` via `julia --up` that you will have access to the correct `julia +`. I do a lot of `python -m pip install ...` in stead of `pip install` when my system gets messy to ensure I don't access some wrong pip from another distribution. You can easily end up in a situation where `juliaup add beta` happily installs a Julia version but `julia +beta` gives an error.
