### ISSUE TITLE
Add a way to see channel of juliaup

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/juliaup#818]
~Something like `juliaup self status` or `juliaup self version` would be nice to tell what version of juliaup I'm using.~

It would also be nice to see which juliaup channel I'm on.

**Comment by davidanthoff** [comment]
`juliaup --version` or `juliaup -V` should do the trick.

But we should definitely add an indication on what channel one is! I think `juliaup self channel` should just not error but show the channel?

**Comment by LilithHafner** [comment]
Oops, yes. You are absolutely right!
