### ISSUE TITLE
Juliainstaller Crash Report

### ISSUE THREAD

**Issue by tobydriscoll** [JuliaLang/juliaup#826]
"name" = "Juliainstaller"
"operating_system" = "Mac OS 13.6.0 [64-bit]"
"crate_version" = "1.13.0"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 794
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/driscoll/.bashrc.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x100526d24 - core::result::unwrap_failed::hc60ef978ea39e1b4
   1: 0x1003978a0 - juliaup::command_config_modifypath::run_command_config_modifypath::h128619761258fbf1
   2: 0x10028be5c - juliainstaller::main::hc82ac1c4f214aa33
   3: 0x100276040 - std::sys_common::backtrace::__rust_begin_short_backtrace::had196ea5bb642008
   4: 0x100276960 - std::rt::lang_start::hb2e78bef159560e2
   5: 0x100291d6c - _main"""

**Comment by tobydriscoll** [comment]
As an update, deleting my .bashrc file allowed the installation to conclude successfully.

**Comment by mkitti** [comment]
Similar to #827 . Was there a permission issue with you .bashrc?

**Comment by tobydriscoll** [comment]
Not that I noticed, but I can't be sure. It would have been either .bash_profile or .zshrc, though.
