### ISSUE TITLE
Installation not possible 

### ISSUE THREAD

**Issue by astro-kevin** [JuliaLang/juliaup#827]
When installing on Mac, the JuliaUp program errors out and generates the following log files. I have changed the file ending from .toml to .log for upload.
[report-0d97f602-4160-4039-ad72-931ce0b78316.log](https://github.com/JuliaLang/julia/files/14196876/report-0d97f602-4160-4039-ad72-931ce0b78316.log)
[report-82f2fba7-156c-438d-800f-dc3cf7c70c7a.log](https://github.com/JuliaLang/julia/files/14196877/report-82f2fba7-156c-438d-800f-dc3cf7c70c7a.log)

**Comment by vtjnash** [comment]
Looks like this should be filed on the juliaup repo:
```
"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.1.2 [64-bit]"
"crate_version" = "1.13.0"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 794
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/s2268228/.bash_profile.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x10109ed24 - core::result::unwrap_failed::hc60ef978ea39e1b4
   1: 0x100f0f8a0 - juliaup::command_config_modifypath::run_command_config_modifypath::h128619761258fbf1
   2: 0x100e03e5c - juliainstaller::main::hc82ac1c4f214aa33
   3: 0x100dee040 - std::sys_common::backtrace::__rust_begin_short_backtrace::had196ea5bb642008
   4: 0x100dee960 - std::rt::lang_start::hb2e78bef159560e2
   5: 0x100e09d6c - _main"""
```

**Comment by DilumAluthge** [comment]
> Looks like this should be filed on the juliaup repo:

Yeah, I've transferred it to the Juliaup repo.

**Comment by mkitti** [comment]
```
"name" = "Juliainstaller"
"operating_system" = "Ubuntu 22.04 (jammy) [64-bit]"
"crate_version" = "1.14.5"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /home/b-ry-jr/.zshrc.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x7f3518fcba65 - juliaup::command_config_modifypath::run_command_config_modifypath::h8c575168682c64d5
   1: 0x7f3518e7851a - juliainstaller::main::h3fc8adcf7e45ce1b
   2: 0x7f3518e5ea03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h36a1912cbf06ac8a
   3: 0x7f3518e5f403 - std::rt::lang_start::h53ae6b99325d4862"""
```

This looks similar.

**Comment by mkitti** [comment]
Second user was able to resolve the issue by fixing access to .zshrc.

@astro-kevin , is there a reason that /Users/s2268228/.bash_profile is inaccessible?

**Comment by astro-kevin** [comment]
I gave write permissions to all users and that seems to have fixed it.

**Comment by mkitti** [comment]
All users? Are you trying to create a multiuser installation? Julia has some distinct facilities to enable this.

**Comment by astro-kevin** [comment]
I'm not, but in the permissions GUI in MacOS, there's the option to enable read/write permissions for system only, myself, or all users. I changed it to all users because that seems to be the most permissive option and it seems to have worked. I probably works if I changed it to myself only, but I didn't test that.
