### ISSUE TITLE
Windows 11 installer

### ISSUE THREAD

**Issue by MrBenzWorld** [JuliaLang/juliaup#835]
Please provide the .exe app for windows.  Or, alternative choice. 
Winget is only for windows insiders , not for windows local login users . 

The Linux version is good. Please fix windows Version too.

**Comment by davidanthoff** [comment]
Take a look at the README, we provide two alternatives to the Windows Store version already. `winget` is not a windows insider thing, it is available on all windows 11 versions, as far as I can tell.

**Comment by KristofferC** [comment]
I think the issue is that the nformation about this is not sufficient on the julia website? (Very few people will go to the README here).

**Comment by MrBenzWorld** [comment]
Tried all as mentioned in Readme ,
The issue is that the app store is required to login with email and insider need to be enabled. 

This is not a desired feature for open source software, or language. 

Offline app install  ( as mentioned) will install only julia not juliaup. 

Some Professor workers can't use juliaup in windows due this. 

Julia needed a good developer community who tried to listen to users problems.

Thank you.

**Comment by KristofferC** [comment]
Doesn't the MSIX App installer work? From the README:

> If the Windows Store is blocked on a system, we have an alternative [MSIX App Installer](https://learn.microsoft.com/en-us/windows/msix/app-installer/app-installer-file-overview) based setup. Note that this is currently experimental, please report back successes and failures https://github.com/JuliaLang/juliaup/issues/343. To use the App Installer version, download [this](https://install.julialang.org/Julia.appinstaller) file and open it by double clicking on it.

**Comment by MrBenzWorld** [comment]
> Doesn't the MSIX App installer work? From the README:
> 
> > If the Windows Store is blocked on a system, we have an alternative [MSIX App Installer](https://learn.microsoft.com/en-us/windows/msix/app-installer/app-installer-file-overview) based setup. Note that this is currently experimental, please report back successes and failures https://github.com/JuliaLang/juliaup/issues/343. To use the App Installer version, download [this](https://install.julialang.org/Julia.appinstaller) file and open it by double clicking on it.

I have tried it, the julia app is installed ,and julia is working. But juliaup is not working. 

If I need to enable any Path additionally please let me know. 

@KristofferC

**Comment by KristofferC** [comment]
To have `juliaup` working it needs to be on the `PATH` where it is installed. So if it currently is not, then you can find out where it is installed and add it to PATH. Ideally, the installer should do this itself so that is something where things could be improved.

**Comment by MrBenzWorld** [comment]
I gave the path. Now, juliaup is working. 
I can add ,or change julia version. 
But, not able to run julia from command. 
If you run julialanucher command ,it is working fine. 

If I give a specific path to the Julia version (.julia/julia-1.8.5+..../bin), I can launch it using the julia command. But if I change the julia version using juliaup ,it is not opening the changed version when I run the julia command. 

julialauncher should run with the julia command.  I think the problem will be solved. @KristofferC

**Comment by davidanthoff** [comment]
The MSIX installer and the Windows Store version are essentially identical, both use the MSIX installation engine to install things at the end of the day. The `PATH` story for MSIX installers is that a setup package declares "execution aliases", and they get automatically placed into a folder `~\AppData\Local\Microsoft\WindowsApps` by the MSIX engine. That folder should be on the `PATH`. Having that folder on the `PATH` is a default on any Windows system, if it isn't, someone must have manually removed it and you should add that folder back to your `PATH`. The Julia MSIX places two execution aliases into that folder: `julia` and `juliaup`.

You should _not_ add a folder like `.julia/julia-1.8.5+..../bin` to your `PATH`, that is not how this is meant to work. In fact, nothing Julia or Juliaup specific should be on your `PATH`, instead the MSIX installer places execution aliases into a known folder that is already on the `PATH`.

> I think the issue is that the nformation about this is not sufficient on the julia website? (Very few people will go to the README here).

Someone should just merge https://github.com/JuliaLang/julia/pull/50477 and then we can link to that from the download page.

**Comment by MrBenzWorld** [comment]
Added this path, 
"~\AppData\Local\Microsoft\WindowsApps"

Now julia and juliaup working from command. 

Please add this  path comment in readme clearly.  Because, juliaup.exe also has another path along with julialauncher.exe.

Thank you. 
@davidanthoff @KristofferC

**Comment by davidanthoff** [comment]
I think we could add this information to some kind of FAQ at the end of the new section on installation in the Julia manual, once that is merged. PRs welcome!

I don't think we should put this prominently, at the end of the day this is a situation that the vast majority of users probably will never encounter, this really should only be a problem if someone manually _removed_ this folder from their `PATH`.
