### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by heetbeet** [JuliaLang/juliaup#86]
The downloading functionality
https://github.com/JuliaLang/juliaup/blob/012249c96fbabe0ae1614c4c76eae1a56fa23ea7/Juliaup/src/Juliaup.jl#L109

could easily use Pkg's MiniProgressBar to add that familiar progress bar:
https://github.com/JuliaLang/Pkg.jl/blob/67ed9cb3541368e3f98867ed809de7c6db32f4cc/src/PlatformEngines.jl#L258

**Comment by davidanthoff** [comment]
Now tracking at https://github.com/JuliaLang/juliaup/issues/102.
