### ISSUE TITLE
Juliaup Crash Report

### ISSUE THREAD

**Issue by arhik** [JuliaLang/juliaup#861]
Occasional panic failures when remote url resources are fetched. May need some timeout handler for graceful exit.

> "name" = "Juliaup"
> "operating_system" = "Mac OS 14.0.0 [64-bit]"
> "crate_version" = "1.14.5"
> "explanation" = """
> Panic occurred in file 'src/operations.rs' at line 1348
> """
> "cause" = "called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"julialangnightlies-s3.julialang.org\")), port: None, path: \"/bin/macos/aarch64/julia-latest-macos-aarch64.tar.gz\", query: None, fragment: None }, source: TimedOut }"
> "method" = "Panic"
> "backtrace" = """
> 
>    0: 0x10252e31c - core::result::unwrap_failed::hc60ef978ea39e1b4
>    1: 0x10237cf2c - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h54bcde48f075e610
>    2: 0x10234ce68 - juliaup::operations::update_version_db::he852f8082ab84e73
>    3: 0x102248ca0 - juliaup::main::h262f175e48e39104
>    4: 0x10223ebf0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3b2098f45e688eda
>    5: 0x10223f234 - std::rt::lang_start::ha7003398882e29b6
>    6: 0x102261d00 - _main"""
> 
>

**Comment by arhik** [comment]
This is a Low priority bug. simply rerunning `juliaup update` will work.

**Comment by mortenpi** [comment]
Just noting that I also ran into this when running `juliaup update nightly`.
