### ISSUE TITLE
Base is not read-only

### ISSUE THREAD

**Issue by 3f6a** [JuliaLang/juliaup#865]
```
julia> @edit LogExpFunctions.logaddexp(4, 5) # opened file is read-only (same happens for any other packages)

julia> @edit sin(4) # opened file is NOT read-only. Seems to occur for all base Julia installation files
```

**Expected behavior:** Base files should also be read-only. Seems permissions are not set correctly during installation?

I tested this on Mac (Apple silicon) and Linux (x86). In both cases I installed Julia via `juliaup` (just ran the script `curl -fsSL https://install.julialang.org | sh`).

```julia
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_EDITOR = mvim
  JULIA_PKG_USE_CLI_GIT = true
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE = eager
```

**Comment by timholy** [comment]
> But we potentially need an update to Revise.jl, to pick whether it wants to track the real (immutable) installed sources or the corresponding (writable) development files

I think Revise should track whatever was running. That is, if you want to edit the development source files, then you should be running a Julia built from those files. In that case I don't think Revise will need any modification.

Just chiming in here that I've been bit by this repeatedly (since juliaup's code is not a git repository, me and Ctrl-Z are getting to be quite good friends), so I'd be enthusiastic to see them made read-only.

**Comment by davidanthoff** [comment]
My understanding is that nothing needs to be done on the Juliaup side, but that the tar balls that Juliaup downloads just need to have the read-only flags set.

**Comment by StefanKarpinski** [comment]
I'm not clear what the hold up here is. Who needs do something? Do we need to change the way our tarballs are generated at build time? Does @staticfloat need to change how they're uploaded?

**Comment by davidanthoff** [comment]
I think we need to change how the tarballs are generated at build time, I believe the files that should be read-only should get that attribute inside the tarball, and then everything should/might work.

**Comment by spaette** [comment]
this ticket is closed

_cf_: https://github.com/JuliaLang/juliaup/issues/865#issuecomment-1992255384

my original command was as follows

`find ~/julia*/share/julia/{base,stdlib,test} -perm 644 -exec chmod 444 {} \;`

and with the commit's interpolated variables, I presume would have been written as

`find $(DESTDIR)$(datarootdir)/julia/{base,stdlib,test} -perm 644 -exec chmod 444 {} \;`
