### ISSUE TITLE
PyCall and PyPlot are crashing in Juliaup for windows since update Julia 1.10

### ISSUE THREAD

**Issue by ay111** [JuliaLang/juliaup#866]
PyCall and PyPlot are crashing in since Julia updated to 1.10. Here is error generated while trying to plot sin(x).

using PyCall,PyPlot
pygui(true)
x=LinRange(0,2pi,100)plot(x,sin.(x))

The terminal process "C:\Users\adeto\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\bin\julia.exe '-i', '--banner=no', '--project=c:\Users\adeto\My Drive\New files\JJULLIA', 'c:\Users\adeto\.vscode\extensions\julialang.language-julia-1.75.2\scripts\terminalserver\terminalserver.jl', '\\.\pipe\vsc-jl-repl-8079a73b-6db7-4fb4-948e-25eb58c5e36e', '\\.\pipe\vsc-jl-cr-5815c0ff-3008-48d5-a472-3db500e536c1', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'ENABLE_SHELL_INTEGRATION=true', 'DEBUG_MODE=false'" terminated with exit code: -1066598274.

**Comment by davidanthoff** [comment]
Couple of things to try:
1. Can you build both packages again? Go into the package manager and just run `pkg> build PyCall` and `pkg> build PyPlot`.
2. Can you try outside of VS Code, i.e. in a regular terminal? We might also get more error info that way.

**Comment by ay111** [comment]
They are still crashing on Juliaup REPL(outside Viscose).

**Comment by davidanthoff** [comment]
I just tried it on 1.9 and 1.10, and it crashes with both. Do we even know that this is related to Juliaup? I would recommend opening and issue over at PyPlot about this, to me this looks more like a problem with that. If it turns out that this is Juliaup related, then please reopen the issue here.

**Comment by ay111** [comment]
I guess the problem is related to Juliaup because both PyCall and PyPlot
are working perfectly in the Julia version I downloaded directly from the
Julia website which I updated with UpdateJulia.jl.
However, PyCall and PyPlot are crashing in the Julia version downloaded and
updated from the microsoft store.
