### ISSUE TITLE
Say which Julia binary is updated when updating

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/juliaup#867]
When I type `juliaup update`, and when it's time to update, then `juliaup` only says
```
  Downloading: [=============>      ] 138.80 MiB/204.70 MiB eta: 12s
```
It doesn't say which Julia binary is being updated – that would be nice to know. For example, a line `updating alpha`, or `Downloading nightly: [====>` would be convenient.

**Comment by davidanthoff** [comment]
I just reverted https://github.com/JuliaLang/juliaup/pull/887, I think that was too chatty with lots of output about things that `juliaup up` didn't do.

I'm also a bit confused about the original issue here, doesn't the line above the "Downloading:" actually say which version is being installed?

**Comment by ghyatzo** [comment]
I apologize for the half assed PR. From the `install_version` function there is the code:
```
    eprintln!(
        "{} Julia {}",
        style("Installing").green().bold(),
        fullversion
    );
```
that prints `fullversion`, it could be easily extended to add some channel information:
```
    eprintln!(
        "{} Julia {} on channel {}",
        style("Installing").green().bold(),
        fullversion,
        channel
    );
```
