### ISSUE TITLE
VS Code with Jupyter extension does not find Julia kernel

### ISSUE THREAD

**Issue by petrposik** [JuliaLang/juliaup#88]
On Windows 10, I installed julia via juliaup. It installed the executable julia file into
`C:\Users\petrp\AppData\Local\Microsoft\WindowsApps\julia.EXE`

I then run VS Code, installed julia extension. It did not find the julia executable automatically, so I manually set up the julia:executable_path to the file path above.
Now, I can run a simple Julia script in a REPL.

In VS Code, I then installed the jupyter extension. When I open an .ipynb file with julia cells, it recognizes the cells as containing Julia code, but does not find Julia kernel. When I click on "Select kernel", it offers only Python kernels I have installed in my system; no Julia kernel.

Am I doing something wrong? Is there a way to setup Julia kernel manually with juliaup?

```
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)       
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64    
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by davidanthoff** [comment]
You should not need to configure anything in the Julia extension, it should find Julia automatically if you just don't configure anything.

Re the notebook stuff: Did you enable that feature in the extension? There is a setting to turn it on.

**Comment by petrposik** [comment]
@davidanthoff, thanks a lot for mentioning the setting to enable the experimental native Jupyter integration. I was not aware of it. It works now for me.
And sorry for making this an issue, I should probably ask on slack/discord first.

**Comment by davidanthoff** [comment]
No problem, glad it is working :)
