### ISSUE TITLE
Juliainstaller Crash Report

### ISSUE THREAD

**Issue by gabmifre** [JuliaLang/juliaup#891]
Trying to install Julia 1.10.2 on macOS v14.4.1, M1 iMac. I previously had Julia 1.9 installed by downloading it, but I deleted it and still have this error. When I type 'julia' in command line, I have no Julia installed. I have tried running the install command (curl) with sudo but still doesn't work. Would be nice to know if there is any way to fix this.

Report file:

```
"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.4.1 [64-bit]"
"crate_version" = "1.14.7"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/g/.bash_profile.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x104736420 - core::result::unwrap_failed::h79c2cb9e4fc28c72
   1: 0x1045a077c - juliaup::command_config_modifypath::run_command_config_modifypath::h7e32c7395314f06d
   2: 0x104491800 - juliainstaller::main::ha5b6681862e25582
   3: 0x10447eab8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h040e90bfea1c4f44
   4: 0x10449665c - _main"""


```

**Comment by Jebrano** [comment]
I also have exactly the same problem, here.
```
"name" = "Juliainstaller"
"operating_system" = "Fedora 39.0.0 [64-bit]"
"crate_version" = "1.14.8"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /home/jubran/.bashrc.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x7fc9fd9e86cd - juliaup::command_config_modifypath::run_command_config_modifypath::hd5a74fa3d14e27b4
   1: 0x7fc9fd8bb8d9 - juliainstaller::main::hc7d4f590be58fbb4
   2: 0x7fc9fd8a38f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4fd42de0f5791891
   3: 0x7fc9fd8c165c - main"""
```

**Comment by ardagabi** [comment]
I will just paste my answer from https://github.com/JuliaLang/juliaup/issues/796:

> I got the exact same crash report.
> 
> Problem caused due to ~/.bash_profile not being owned by the user attempting to edit the file.
> 
> Change ownership of .bash_profile:
> sudo chown {username} ~/.bash_profile
> 
> Then got same error but this time mentioning .zshrc. Again, same solution:
> sudo chown {username} ~/.zshrc
> 
> After this installation was successful.

**Comment by Jebrano** [comment]
I forgot to come back and update, I got it working fine, for some reasons my `zsh` configuration files that were used by julia installer had a different owner, so I could not run them as sudo, I just had to mess with them a bit before retrying to install julia.
