### ISSUE TITLE
Julia Install Crash Report

### ISSUE THREAD

**Issue by celise88** [JuliaLang/juliaup#918]
"name" = "Juliainstaller"
"operating_system" = "Mac OS 12.7.0 [64-bit]"
"crate_version" = "1.14.8"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/caitlinlahuis/.bash_profile.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x1044d1ab4 - core::result::unwrap_failed::h71a35eff74d84b68
   1: 0x104383ddc - juliaup::command_config_modifypath::run_command_config_modifypath::hfba9ff76b3bf9106
   2: 0x104291458 - juliainstaller::main::h58826e7c28086c63
   3: 0x10427ddf0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc479014f54c9f9ef
   4: 0x104295940 - _main"""

**Comment by jybantang** [comment]
Unfortunately, one has to force removal of traces of `Julia` and `juliaup` in several profile files using the `su`. This should not be the case.

I manage to successfully remove `juliaup` installation via the `sudo` command.

```
$ sudo juliaup self uninstall
``` 

The cause is the `juliaup` seems to have been denied permission to edit some of the profile files under one's home account.

**Comment by jybantang** [comment]
Well, apparently, the installation sequence does not work as well in my box. So likely that this is more fundamental than I expected. Sorry.

**Comment by celise88** [comment]
No worries.  Not that this helps you, but for anyone else with similar issues, this worked for me: 

sudo chmod 777 /private/tmp
brew install julia

**Comment by ardagabi** [comment]
I will just paste my answer from #796:

> I got the exact same crash report.
> 
> Problem caused due to ~/.bash_profile not being owned by the user attempting to edit the file.
> 
> Change ownership of .bash_profile:
> sudo chown {username} ~/.bash_profile
> 
> Then got same error but this time mentioning .zshrc. Again, same solution:
> sudo chown {username} ~/.zshrc

After this installation was successful.
