### ISSUE TITLE
Fail to install with curl

### ISSUE THREAD

**Issue by ShuhuaGao** [JuliaLang/juliaup#934]
With or without `sudo`, I have 
```bash
shuhua@node01:~/downloads$ sudo curl -fsSL https://install.julialang.org | sh

info: downloading installer
curl: (23) Failure writing output to destination
juliaup: command failed: downloader https://julialang-s3.julialang.org/juliaup/bin/juliainstaller-1.14.8-x86_64-unknown-linux-musl /tmp/tmp.esqzfwitoQ/juliainstaller x86_64-unknown-linux-musl
```
Is there other way I can install juliaup?

Besides, I can download the link *https://julialang-s3.julialang.org/juliaup/bin/juliainstaller-1.14.8-x86_64-unknown-linux-musl * directly with firefox, but I don't know how to install *juliainstaller-1.14.8-x86_64-unknown-linux-musl* manually.

**Comment by StefanKarpinski** [comment]
Seems like maybe you are getting a temp directory that you cannot write to?

**Comment by ShuhuaGao** [comment]
Thanks for your suggestion. I checked it and can indeed create directory and files under /tmp manually. So it is not a privilege issue. 

Besides, I just noticed from the error information that it tries to write `/tmp/tmp.esqzfwitoQ/juliainstaller x86_64-unknown-linux-musl`. Is the space between `juliainstaller` and `x86` an error?

**Comment by ShuhuaGao** [comment]
I am not sure whether curl can write to /tmp or not on my system, a newly installed Ubuntu 22.04. 
```
shuhua@node01:~/downloads$ which curl
/snap/bin/curl
```
But I managed to install juliaup manually as follows.
```bash
shuhua@node01:~/downloads$ curl -fsSL https://julialang-s3.julialang.org/juliaup/bin/juliainstaller-1.14.8-x86_64-unknow
n-linux-musl -o ./jlinstall

shuhua@node01:~/downloads$ chmod +x ./jlinstall

shuhua@node01:~/downloads$ ./jlinstall
```
