### ISSUE TITLE
`curl_easy_setopt: 4` when using Pkg due to old libcurl version

### ISSUE THREAD

**Issue by alex180500** [JuliaLang/juliaup#936]
In windows with a fresh install of `juliaup` with Julia 1.10.3 when using any command in the Pkg REPL gives out this message:
```jl
┌ Error: curl_easy_setopt: 4
└ @ Downloads.Curl C:\Users\aless\.julia\juliaup\julia-1.10.3+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Downloads\src\Curl\utils.jl:50
```
Everything is working correctly but there is this error continuously

**Comment by alex180500** [comment]
Sorry maybe this is more of a problem of the `Downloads.jl` package. I reposted here: https://github.com/JuliaLang/Downloads.jl/issues/244

**Comment by alex180500** [comment]
I think now that this is related to the version of libcurl included in `julia-1.10.3+0.x64.w64.mingw32\bin\libcurl-4.dll`

**Comment by KristofferC** [comment]
What makes you say that?

**Comment by StefanKarpinski** [comment]
Can we have the conversation in one place?
