### ISSUE TITLE
Problem with installation of Julia / Juliainstaller Crash Report

### ISSUE THREAD

**Issue by BrunoFreitas6** [JuliaLang/juliaup#946]
Hello,
I was following the instructions of installation at https://julialang.org/downloads/#install_julia, but when writing "curl -fsSL https://install.julialang.org | sh" on the terminal, the following error appears:

"Well, this is embarrassing.

Juliainstaller had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/var/folders/50/g7hny87d7m93bw7qqw98vw5h0000gn/T/report-46953da4-1f2a-4ee6-8919-66701c29f3a0.toml". Submit an issue or email with the subject of "Juliainstaller Crash Report" and include the report as an attachment.

To submit the crash report:

https://github.com/JuliaLang/juliaup

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!"

I attach the report below, as requested.:

"
"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.5.0 [64-bit]"
"crate_version" = "1.14.8"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/estev043/.bash_profile.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x1042c9ab4 - core::result::unwrap_failed::h71a35eff74d84b68
   1: 0x10417bddc - juliaup::command_config_modifypath::run_command_config_modifypath::hfba9ff76b3bf9106
   2: 0x104089458 - juliainstaller::main::h58826e7c28086c63
   3: 0x104075df0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc479014f54c9f9ef
   4: 0x10408d940 - _main"""
"
Thank you.

**Comment by christiangnrd** [comment]
This seems like a duplicate of #796 and #875.

**Comment by BrunoFreitas6** [comment]
I followed the instructions on those issues and it worked perfectly.
Thank you!
