### ISSUE TITLE
Feature Request: FreeBSD support

### ISSUE THREAD

**Issue by torculus** [JuliaLang/juliaup#963]
Considering that [https://julialang.org/downloads/](https://julialang.org/downloads/) officially lists FreeBSD as having Tier 2/3 support, would it be possible to add FreeBSD support to `juliaup`?

**Comment by davidanthoff** [comment]
https://github.com/JuliaLang/juliaup/pull/872

**Comment by torculus** [comment]
Whoops! I checked issues, but not open pull requests. Sorry!

**Comment by ararslan** [comment]
@torculus, the PR for FreeBSD support has now been merged, so you should be able to use JuliaUp to manage Julia installations on FreeBSD soon!
