### ISSUE TITLE
Investigate homebrew on MacOS

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#97]
One question is whether we would publish it as `julia`, or `juliaup`. Clearly `julia` is only an option down the road if we decide that `juliaup` becomes the default, official installer. But if that happens at some point, it might be nice?

**Comment by DilumAluthge** [comment]
`julia` already exists in Homebrew as both a formula (https://formulae.brew.sh/formula/julia) and a cask (https://formulae.brew.sh/cask/julia).

If I understand correctly, the `julia` cask simply downloads the official release binaries, so it may be fine to keep the cask as-is.

However, I do think it would be a good idea for us to investigate if we can replace the `julia` formula with `juliaup`.

**Comment by nathanrboyer** [comment]
Installing `juliaup` with Homebrew and then `julia` with `juliaup` sounds like an unnecessary extra step. I like being able to run `brew up` to update all my formulae, including Julia. If the `julia` Homebrew formula becomes `juliaup`, then I would need two commands to achieve the same thing. I am using `juliaup` only on Windows because Homebrew doesn't exist for Windows.

**Comment by davidanthoff** [comment]
Yes, that is a good step. I think the only way around that would be to have some ability to have certain channels configured (locally) as completely auto-update. So `juliaup` could be updated by `brew`, and if say the `release` channel is configured for auto-update, then when you update `juliaup`, the `release` channel would automatically also update to the latest Julia version in it.

**Comment by deoradh** [comment]
@davidanthoff Guessing this can be closed as of 1.5.29? :)

**Comment by davidanthoff** [comment]
Alright, for now we have `juliaup` in homebrew now. New builds are automatically pushed to hombrew-core, so this is all fully automated.

**Comment by musm** [comment]
> Yes, that is a good step. I think the only way around that would be to have some ability to have certain channels configured (locally) as completely auto-update. So `juliaup` could be updated by `brew`, and if say the `release` channel is configured for auto-update, then when you update `juliaup`, the `release` channel would automatically also update to the latest Julia version in it.

If I understand correctly. `juliaup` installed via brew then updated via `brew up` will update the default Julia channel configured in `juliaup` ?

I am wondering if the warnings regarding using homebrew on the home page are no longer necessary?

**Comment by davidanthoff** [comment]
Oh, much better: the channel information will be auto-updated continuously, entirely independent of anything happening with brew. The warning is probably no longer necessary.
