### ISSUE TITLE
`Error: No such file or directory (os error 2)` on Linux

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/juliaup#98]
This is using the provided v1.0.63 binaries as well as when I build from source:
```
[simeon@majestix target\x86_64-unknown-linux-gnu]$ ./juliaup add 1
Installing Julia 1.6.2+0 (x64).
Error: No such file or directory (os error 2)
```

I am using Manjaro Linux. Any ideas why this would happen?

**Comment by davidanthoff** [comment]
Hm, I really need to add better error messages that give us some clue where this is going wrong :)

**Comment by davidanthoff** [comment]
If you want to try to dig into that yourself, it is actually _reallly_ simple to try: just install rustup, and then in the root folder of this git repo run `cargo run -- add 1` and that will compile and run `juliaup`. But I'm not sure you would see any more helpful errors...

**Comment by simeonschaub** [comment]
Yeah, unfortunately that doesn't give anything more helpful:
```
[simeon@majestix juliaup]$ RUST_BACKTRACE=1 cargo run -- add 1
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/juliaup add 1`
Installing Julia 1.6.2+0 (x64).
Error: No such file or directory (os error 2)
```

**Comment by simeonschaub** [comment]
Looks like it didn't create the folder `~/.julia/juliaup` automatically, it probably should, right?

Now I get a different error:
```
[simeon@majestix juliaup]$ RUST_BACKTRACE=1 cargo run -- add 1
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/juliaup add 1`
Installing Julia 1.6.2+0 (x64).
target: /home/simeon/.julia/juliaup/julia-1.6.2+0~x64
tmp_dir /tmp/juliaupgJSl5b
baz
foo
Error: Invalid cross-device link (os error 18)
```

It seems to still be caused by this line:
https://github.com/JuliaLang/juliaup/blob/7a61e3091c0b217bd4de0b8214fe14f83cd0a8cc/src/operations.rs#L69

I believe on my system, `/tmp/` is a RAM disk, which could be why `fs::rename` fails, because my home folder is a different file system.

**Comment by davidanthoff** [comment]
Yeah, at the moment I have an assumption built in that users will _first_ run the launcher once (which will setup everything) and only then start to use `juliaup`. That obviously doesn't make sense, so I need to just go through `juliaup` and make sure it all works properly for a scenario where nothing is on disc yet. So that would hopefully fix your first problem.

The second one is interesting :) I thought the `rename` story would make things more robust, but apparently not :) Maybe we just extract directly into the target folder and skip the entire temporary folder?

**Comment by simeonschaub** [comment]
> Maybe we just extract directly into the target folder and skip the entire temporary folder?

Yes, that seems reasonable to me.

**Comment by davidanthoff** [comment]
I just realized why that won't work, though: we need to skip one level of folders...

**Comment by davidanthoff** [comment]
https://users.rust-lang.org/t/moving-and-renaming-directory/44742/2 might work, though...
