### ISSUE TITLE
Allow overriding an override

### ISSUE THREAD

**Issue by visr** [JuliaLang/juliaup#987]
I just discovered overrides, which work great, though I have one suggestion on setting overrides.

Currently if you set an override on a path that already has an override, you get an error and the override does not change:

```
❯ juliaup override set 1.10.4

❯ juliaup override set 1.10.4
Error: '\\?\D:\repo\ribasim\Ribasim' path already has an override configured.
```

This means that the only way to reliably set an override is this, because `unset` luckily doesn't error if it is already `unset`:

```
juliaup override unset
juliaup override set 1.10.4
```

I feel like if a user asks for a valid override, that should be done, rather than erroring out.

**Comment by mitiemann** [comment]
Also, if you try to `juliaup override set [channel]` which has not been `juliaup add [channel]`, the confusing error message `Error: '[channel]' does not exist.` is displayed. It should be possible to search whether `'[channel]` is available on the channel list and then something like
`Error: '[channel]' does not exist locally, but is available remotely. Do you want to add it now [y/n]:`
would be a nice feature.

**Comment by davidanthoff** [comment]
Both excellent feature suggestions!

**Comment by mitiemann** [comment]
> I feel like if a user asks for a valid override, that should be done, rather than erroring out.

Although probably you should print a warning. Otherwise an user might accidentally loosen an override, e.g.,
```
> juliaup override set 1.10.1

> juliaup override set 1.10
```
and you'd suddenly get `1.10.4` (maybe a bad example, but I think the principle applies).
