### ISSUE TITLE
Throws "Invalid Juliaup channel `pr55132`" despite channel being valid

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/juliaup#995]
```
x@x:~/.julia/dev/julia$ julia +pr55132
ERROR: Invalid Juliaup channel `pr55132`. Please run `juliaup list` to get a list of valid channels and versions.
x@x:~/.julia/dev/julia$ juliaup add pr55132
Installing Julia pr55132-linux-aarch64
```

See also #980, #766, #820

**Comment by christiangnrd** [comment]
From #820. I'm moving the conversation here as I've decided #848 won't try to fix PRs too.

>I was working on the merge conflicts in rebasing #848 to main earlier and it got me wondering how  PR channels should be considered. 
>
>Potential options I came up with:
>1. Treat them like any invalid channel. (easy option)
>2. Look online to see if it’s a valid pr with an uploaded build and show the uninstalled channel message. (Would have to connect to the internet for a step that doesn’t typically need to)
>3. Find a concise way to explain that it may or may not be a valid channel that happens to be uninstalled. (Every phrasing I come up with for this feels sloppy and drawn out)
>
>Any ideas?
>
>_Originally posted by @christiangnrd in https://github.com/JuliaLang/juliaup/issues/820#issuecomment-2229892967_

>It seems reasonable to me to only know about the PRs available as of the last update. If you want a new PR do an update?
>
>_Originally posted by @StefanKarpinski in https://github.com/JuliaLang/juliaup/issues/820#issuecomment-2230651453_

@StefanKarpinski I don't believe the local database has a list of available PRs, so it would have to try to download at least the header to check that that PR is available.

**Comment by christiangnrd** [comment]
Potential message for point 3: 
```
`pr{number}` is not installed. Please run `juliaup add pr{number}` to install pull request if available.
```

**Comment by LilithHafner** [comment]
Yep, I agree that the best would be to treat them as channels that _are_ available, with a little extra text ("...if available"). Functionally, they are channels, so I would say "to install pull request channel if available."

Maybe this goes without saying, but `{number}` should be interpolated so the user never sees it.
